import { existsSync, mkdtempSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  SITEBUILDER_FILE,
  WORKFLOW_FILE,
  installPages,
  pagesState,
  sitebuilderPath,
  workflowYaml,
} from '../pages.js';

const scratch = (): string => mkdtempSync(join(tmpdir(), 'vn-pages-'));

describe('workflowYaml', () => {
  it('triggers on the branch it was installed from and publishes to the named one', () => {
    const yaml = workflowYaml('main', 'gh-pages');
    expect(yaml).toContain('branches: [main]');
    expect(yaml).toContain('PUBLISH_BRANCH: gh-pages');
  });

  it('runs the renderer from the path the installer writes it to', () => {
    expect(workflowYaml('master', 'gh-pages')).toContain(`node ${SITEBUILDER_FILE} --project .`);
  });

  it('refuses a publish branch it did not write, by looking for the marker', () => {
    const yaml = workflowYaml('main', 'pages');
    expect(yaml).toContain('git cat-file -e FETCH_HEAD:.vn-pages');
    expect(yaml).toContain('::error::');
    // The marker check has to come before the force push
    expect(yaml.indexOf('cat-file')).toBeLessThan(yaml.indexOf('git push -f'));
  });

  it('keeps one publish per ref rather than one across the repository', () => {
    expect(workflowYaml('main', 'gh-pages')).toContain('group: vn-pages-${{ github.ref }}');
  });
});

/**
 * The bundled renderer is a build artifact, so these are skipped on a checkout that has only run
 * `pnpm check`. `commands.test.ts` skips its generated-catalog test the same way.
 */
const built = ((): boolean => {
  try {
    return existsSync(sitebuilderPath());
  } catch {
    return false;
  }
})();
const whenBuilt = built ? describe : describe.skip;

whenBuilt('installPages', () => {
  it('writes both files, records the merge attribute, and names what it wrote', async () => {
    const root = scratch();
    const written = await installPages(root, { branch: 'main', publishBranch: 'gh-pages' });

    expect(written).toEqual([WORKFLOW_FILE, SITEBUILDER_FILE, '.gitattributes']);
    expect(existsSync(join(root, WORKFLOW_FILE))).toBe(true);
    expect(readFileSync(join(root, SITEBUILDER_FILE), 'utf8')).toContain('Generated by VN Studio');
    expect(readFileSync(join(root, '.gitattributes'), 'utf8')).toContain(
      `${SITEBUILDER_FILE} -merge`,
    );
  });

  it('leaves an existing .gitattributes alone apart from the one line it needs', async () => {
    const root = scratch();
    writeFileSync(join(root, '.gitattributes'), '*.jsonl merge=union\n');
    await installPages(root, { branch: 'main', publishBranch: 'gh-pages' });
    await installPages(root, { branch: 'main', publishBranch: 'gh-pages' });

    const attributes = readFileSync(join(root, '.gitattributes'), 'utf8');
    expect(attributes).toContain('*.jsonl merge=union');
    expect(attributes.match(/vn-site\.mjs -merge/g)).toHaveLength(1);
  });
});

whenBuilt('pagesState', () => {
  const opts = { branch: 'main', publishBranch: 'gh-pages' };

  it('reports nothing installed when only one half is present', async () => {
    const root = scratch();
    mkdirSync(join(root, '.github', 'workflows'), { recursive: true });
    writeFileSync(join(root, WORKFLOW_FILE), workflowYaml(opts.branch, opts.publishBranch));

    expect(await pagesState(root, opts)).toEqual({ installed: false, stale: false });
  });

  it('reports a fresh install as installed and current', async () => {
    const root = scratch();
    await installPages(root, opts);
    expect(await pagesState(root, opts)).toEqual({ installed: true, stale: false });
  });

  it('reports an edited copy as stale', async () => {
    const root = scratch();
    await installPages(root, opts);
    writeFileSync(join(root, SITEBUILDER_FILE), '// somebody edited this\n');

    expect(await pagesState(root, opts)).toEqual({ installed: true, stale: true });
  });

  it('reports a workflow installed for another branch as stale', async () => {
    const root = scratch();
    await installPages(root, { branch: 'master', publishBranch: 'gh-pages' });

    expect(await pagesState(root, opts)).toEqual({ installed: true, stale: true });
  });
});
