/**
 * The History pane's situations: one repository with saves of every maker, two repositories with
 * a filter on, a project inside a foreign repository, an empty history, a save with a diff open
 * in each width, the recovery controls answered by their checks, the sync view with and without
 * shared copies, a sync stopped on a collision, and one still running.
 */
import { situations } from './situation.js';
import { NO_FILTER, type HistoryState } from '../history.js';
import type { RepoStatus, Save } from '../../../src/shared/history.js';

const PROJECT = { role: 'project' as const, root: 'C:/stories/rooftop', owned: true };
const WIKI = { role: 'wiki' as const, root: 'C:/stories/rooftop/wiki', owned: true };

const CLEAN: RepoStatus = {
  cause     : 'clean',
  outside   : [],
  conflicted: [],
  pending   : 0,
  branch    : 'main',
  upstream  : 'origin/main',
  ahead     : 3,
  behind    : 0,
  remotes: [
    {
      name     : 'origin',
      url      : 'https://github.com/mara/rooftop.git',
      ahead    : 3,
      behind   : 0,
      syncsWith: true,
    },
  ],
  lastFetch : '2026-09-21T09:00:00Z',
  inProgress: { rebase: null, merge: false, revert: false },
  replaying : null,
};

const save = (over: Partial<Save> & { sha: string }): Save => ({
  parents    : ['0'.repeat(40)],
  author     : 'VN Studio',
  email      : 'vnstudio@localhost',
  date       : '2026-09-21T14:02:00+00:00',
  subject    : 'Moved line L4 into rooftop',
  body       : '',
  trailers: {
    'Vn-Command'   : 'story.moveLine',
    'Vn-Invocation': "story.moveLine(lineId='L4' toScene='rooftop')",
    'Vn-Source'    : 'ui',
  },
  files      : [{ path: 'scenes/rooftop.fountain', added: 3, removed: 1 }],
  maker      : 'author',
  checkpoints: [],
  sent       : false,
  ...over,
});

const SAVES: Save[] = [
  save({ sha: 'a'.repeat(40) }),
  save({
    sha     : 'b'.repeat(40),
    subject : 'Agent turn: make the rooftop scene tenser',
    trailers: {
      'Vn-Command'   : 'agent.run',
      'Vn-Invocation': "agent.run(input='make the rooftop scene tenser')",
      'Vn-Source'    : 'ui',
    },
    maker   : 'agent',
    date    : '2026-09-21T13:40:00+00:00',
    files: [
      { path: 'scenes/rooftop.fountain', added: 12, removed: 4 },
      { path: 'vngen/state/commands.jsonl', added: 2, removed: 0 },
      { path: 'vngen/state/threads/20260921-133000.jsonl', added: 6, removed: 0 },
    ],
  }),
  save({
    sha        : 'c'.repeat(40),
    subject    : 'Generated 14 assets',
    trailers   : { 'Vn-Command': 'pipeline.run', 'Vn-Source': 'menu' },
    maker      : 'pipeline',
    date       : '2026-09-20T18:42:00+00:00',
    checkpoints: ['before-the-rain-pass'],
    sent       : true,
    files      : [{ path: 'vngen/build/assets/ab12.png', added: null, removed: null }],
  }),
];

export const SITUATIONS = situations<HistoryState>(
  {
    name : 'one-repo',
    why: 'One repository, so no chooser is drawn; three rows of three makers, one selected; every filter off, so Show all is refused; more saves remain, so Earlier saves is offered. The selected save is the author’s own, so opening a conversation is refused.',
    state: {
      repos        : [PROJECT],
      repo         : 'project',
      filter       : NO_FILTER,
      status       : CLEAN,
      saves        : SAVES,
      next         : 'c'.repeat(40),
      selected     : 'a'.repeat(40),
      logsOpen     : false,
      size         : 'large',
      showingDetail: false,
      verdicts     : {},
      syncOpen     : false,
    },
  },
  {
    name : 'two-repos-filtered',
    why: 'The story bible is its own repository, so the chooser lists both; the list is narrowed to one file and to the agent, so the chip and Show all are offered; the history has ended, so Earlier saves is refused.',
    state: {
      repos        : [PROJECT, WIKI],
      repo         : 'project',
      filter: { who: 'agent', path: 'scenes/rooftop.fountain', text: '', checkpointsOnly: false },
      status       : CLEAN,
      saves        : [SAVES[1]!],
      next         : null,
      logsOpen     : false,
      size         : 'large',
      showingDetail: false,
      verdicts     : {},
      syncOpen     : false,
    },
  },
  {
    name : 'agent-save-open',
    why: 'An agent’s save is selected at full width with a diff open beneath its files: the conversation is offered, the logs are folded behind their count, and no way back is drawn because the file list is still on screen.',
    state: {
      repos        : [PROJECT],
      repo         : 'project',
      filter       : NO_FILTER,
      status       : CLEAN,
      saves        : SAVES,
      next         : null,
      selected     : 'b'.repeat(40),
      file         : 'scenes/rooftop.fountain',
      logsOpen     : false,
      size         : 'large',
      showingDetail: false,
      verdicts     : {},
      syncOpen     : false,
    },
  },
  {
    name : 'mid-diff-open',
    why: 'Two narrow columns with a diff open in the file list’s place, and the logs unfolded: the way back to the files is offered, and every file including the logs is listed.',
    state: {
      repos        : [PROJECT],
      repo         : 'project',
      filter       : NO_FILTER,
      status       : CLEAN,
      saves        : SAVES,
      next         : null,
      selected     : 'b'.repeat(40),
      file         : 'scenes/rooftop.fountain',
      logsOpen     : true,
      size         : 'mid',
      showingDetail: false,
      verdicts     : {},
      syncOpen     : false,
    },
  },
  {
    name : 'narrow-detail',
    why: 'The pane is one column wide and a row is open, so the way back to the list is offered above the detail.',
    state: {
      repos        : [PROJECT],
      repo         : 'project',
      filter       : NO_FILTER,
      status       : CLEAN,
      saves        : SAVES,
      next         : null,
      selected     : 'b'.repeat(40),
      logsOpen     : false,
      size         : 'small',
      showingDetail: true,
      verdicts     : {},
      syncOpen     : false,
    },
  },
  {
    name : 'empty',
    why: 'A repository with nothing but its first commit filtered away by the checkpoint tick: no rows, so no paging control, and Show all is offered.',
    state: {
      repos        : [PROJECT],
      repo         : 'project',
      filter       : { ...NO_FILTER, checkpointsOnly: true },
      status       : { ...CLEAN, upstream: null, ahead: null, behind: null, remotes: [] },
      saves        : [],
      next         : null,
      logsOpen     : false,
      size         : 'large',
      showingDetail: false,
      verdicts     : {},
      syncOpen     : false,
    },
  },
  {
    name : 'no-repo',
    why: 'The project is not under version control, so the filters are drawn but there is nothing to list and no repository to choose.',
    state: {
      repos        : [],
      repo         : 'project',
      filter       : NO_FILTER,
      saves        : [],
      next         : null,
      logsOpen     : false,
      size         : 'large',
      showingDetail: false,
      verdicts     : {},
      syncOpen     : false,
    },
  },
  {
    name : 'outside-edits',
    why: 'Two files were changed outside the app, so the status view offers Save these…; the selected save was written over by a later one, so the check refuses taking it back by name while going back is accepted, and the open file can be brought back.',
    state: {
      repos        : [PROJECT],
      repo         : 'project',
      filter       : NO_FILTER,
      status       : { ...CLEAN, cause: 'outside', outside: ['wiki/houses.md', 'project.yaml'] },
      saves        : SAVES,
      next         : null,
      selected     : 'b'.repeat(40),
      file         : 'scenes/rooftop.fountain',
      logsOpen     : false,
      size         : 'large',
      showingDetail: false,
      verdicts: {
        'git.takeBack': {
          ok     : false,
          message:
            'scenes/rooftop.fountain was changed again in 1 later save; go back to a save instead, or bring back the file.',
        },
        'git.goBack': {
          ok     : true,
          message:
            'Restores 2 files to how they were at that save, as a new save. Nothing in history is deleted.',
        },
        'git.restoreFile': {
          ok     : true,
          message: 'Rewrites scenes/rooftop.fountain as it was at save bbbbbbb.',
        },
      },
      syncOpen     : false,
    },
  },
  {
    name : 'checkpointed',
    why: 'The selected save carries a checkpoint, so its name can be dropped from the detail header; the checkpoint button names this save rather than the latest; a take-back was just run, so the footer says the undo history from before no longer applies.',
    state: {
      repos        : [PROJECT],
      repo         : 'project',
      filter       : NO_FILTER,
      status       : CLEAN,
      saves        : SAVES,
      next         : null,
      selected     : 'c'.repeat(40),
      logsOpen     : false,
      size         : 'large',
      showingDetail: false,
      verdicts     : {},
      syncOpen     : false,
      undoBlocked  : "git.takeBack(repo='project' sha='aaaaaaa')",
    },
  },
  {
    name : 'foreign-repo',
    why: 'The project sits inside a repository that is not its own, so every write is refused with the one sentence while the reads still work.',
    state: {
      repos        : [{ ...PROJECT, root: 'C:/stories', owned: false }],
      repo         : 'project',
      filter       : NO_FILTER,
      status       : CLEAN,
      saves        : SAVES,
      next         : null,
      selected     : 'a'.repeat(40),
      logsOpen     : false,
      size         : 'large',
      showingDetail: false,
      verdicts     : {},
      syncOpen     : false,
    },
  },
  {
    name : 'sync-view',
    why: 'The sync view has the detail column, with two shared copies: the GitHub one the project syncs with, which is behind so sending to it is refused until their saves are got, and a backup on a drive that has never been compared. Adding another copy is offered at the foot.',
    state: {
      repos        : [PROJECT],
      repo         : 'project',
      filter       : NO_FILTER,
      status: {
        ...CLEAN,
        ahead  : 3,
        behind : 1,
        remotes: [
          { ...CLEAN.remotes[0]!, behind: 1 },
          {
            name     : 'backup',
            url      : 'D:/backup/rooftop.git',
            ahead    : null,
            behind   : null,
            syncsWith: false,
          },
        ],
      },
      saves        : SAVES,
      next         : null,
      selected     : 'a'.repeat(40),
      logsOpen     : false,
      size         : 'large',
      showingDetail: false,
      verdicts: {
        'git.pull': {
          ok     : true,
          message:
            'Gets their saves from “origin” and replays yours on top. A collision waits for your decision.',
        },
      },
      syncOpen     : true,
    },
  },
  {
    name : 'no-remotes',
    why: 'The sync view is open on a repository with no shared copy, so it says so and leads with connecting one; there is nothing to get from and nothing to send to.',
    state: {
      repos        : [PROJECT],
      repo         : 'project',
      filter       : NO_FILTER,
      status       : { ...CLEAN, upstream: null, ahead: null, behind: null, remotes: [] },
      saves        : SAVES,
      next         : null,
      logsOpen     : false,
      size         : 'large',
      showingDetail: false,
      verdicts     : {},
      syncOpen     : true,
    },
  },
  {
    name : 'conflict',
    why: 'Getting their saves stopped on the second of three replayed saves, with a scene and a layout in question: the scene offers Open both while the layout, which git never merges, offers only the two sides; Continue is refused until both are decided; the status view leads to this view rather than duplicating Give up.',
    state: {
      repos        : [PROJECT],
      repo         : 'project',
      filter       : NO_FILTER,
      status: {
        ...CLEAN,
        cause     : 'rebase',
        conflicted: ['scenes/rooftop.fountain', '.vnstudio/layouts/writing.json'],
        inProgress: {
          rebase: {
            branch    : 'main',
            onto      : 'f'.repeat(40),
            current   : 2,
            total     : 3,
            stoppedSha: 'a'.repeat(40),
            origHead  : 'e'.repeat(40),
          },
          merge : false,
          revert: false,
        },
        replaying: {
          sha    : 'a'.repeat(40),
          subject: 'Moved line L4 into rooftop',
          current: 2,
          total  : 3,
        },
      },
      saves        : SAVES,
      next         : null,
      selected     : 'a'.repeat(40),
      logsOpen     : false,
      size         : 'large',
      showingDetail: false,
      verdicts     : {},
      syncOpen     : false,
      bothOpen     : 'scenes/rooftop.fountain',
    },
  },
  {
    name : 'syncing',
    why: 'A pull is still running, so every write in the sync view and the bar refuses with “Still getting their saves.” while the filters, which only read, stay offered.',
    state: {
      repos        : [PROJECT],
      repo         : 'project',
      filter       : NO_FILTER,
      status       : CLEAN,
      saves        : SAVES,
      next         : null,
      selected     : 'a'.repeat(40),
      logsOpen     : false,
      size         : 'large',
      showingDetail: false,
      verdicts     : {},
      syncOpen     : true,
      syncing      : 'pull',
    },
  },
);
