/**
 * The node graph an asset is generated by. This package is the only door onto path.ux's
 * graph module: everything else in the repository reaches nodes, sockets and graphs
 * through here, so one import path carries the vendor alias and the node registry stays
 * a single map. It reaches no `fs` of its own and no DOM, because the desktop renderer,
 * the CLI and the authoring agent all load the same graph files. Everything that does
 * touch the filesystem is reached through `@vn/gengraph/state` instead, and so does the
 * executor, because it hashes each node through `@vn/util` and that reaches `node:crypto`.
 * The slot vocabulary
 * comes from `@vn/artgen/slotaddr` rather than that package's barrel, which reaches
 * `node:fs/promises` and would fail the renderer's bundle without failing either typecheck.
 */
export * from 'pathux-graph';

export * from './registry.js';
export * from './services.js';
export * from './graphfile.js';
export * from './validate.js';
export * from './slots.js';
export * from './journal.js';
export * from './dsl.js';
export * from './edit.js';
export * from './cost.js';
export * from './prices.js';
export * from './nodes/index.js';
