/**
 * The node graph an asset is generated by. This package is the only door onto path.ux's
 * graph module: everything else in the repository reaches nodes, sockets and graphs
 * through here, so one import path carries the vendor alias and the node registry stays
 * a single map. It reaches no `fs` of its own and no DOM, because the desktop renderer,
 * the CLI and the authoring agent all load the same graph files. Everything that does
 * touch the filesystem is reached through `@vn/gengraph/state` instead. One import is
 * still node-side: `validate.ts` takes the slot vocabulary from `@vn/artgen`, whose barrel
 * reaches `node:fs/promises`, so the renderer cannot load this entry until that vocabulary
 * moves somewhere pure (recorded under Stage 10 of the plan).
 */
export * from 'pathux-graph';

export * from './registry.js';
export * from './services.js';
export * from './graphfile.js';
export * from './validate.js';
export * from './journal.js';
export * from './dsl.js';
export * from './cost.js';
export * from './prices.js';
export * from './nodes/index.js';
