/**
 * The desktop app's command vocabulary. One registry serves the palette, the menu bar, the
 * DSL, and CDP; `catalog-entry.ts` projects this same registry into the build-time JSON.
 *
 * The definitions are thin wrappers over `WorkspaceSession` — the session stays the place
 * where backend logic lives, and commands only add naming, typed props, and provenance.
 */
import { CommandRegistry } from '@vn/commands';
import {
  agentClear,
  agentNewThread,
  agentOpenThread,
  agentRenameThread,
  agentRun,
  agentSetBudget,
  agentSetEffort,
  agentSetMode,
  agentSetModel,
  agentStop,
  agentThreads,
} from './agent.js';
import { artGenerate, artPromote, artRedraw, artSetNotes, artSetSeed } from './art.js';
import {
  assetAccept,
  assetAdopt,
  assetInfo,
  assetRegenerate,
  assetReplace,
  assetSuspended,
  assetUpload,
} from './asset.js';
import { bibleSearch } from './bible.js';
import { commandCheck } from './command.js';
import { docCreate, docRead, docRename, docWrite } from './doc.js';
import { gateApprove, gateCandidates } from './gate.js';
import { interactionList, interactionTargets } from './interaction.js';
import {
  notifyClear,
  notifyDeleteAll,
  notifyFollow,
  notifyHide,
  notifyList,
  notifyMarkRead,
  notifyUnhide,
} from './notify.js';
import { pipelineRun, pipelineStatus, pipelineStop } from './pipeline.js';
import {
  promptAddRef,
  promptCheck,
  promptClear,
  promptCondense,
  promptDropRef,
  promptInfo,
  promptMoveChunk,
  promptRepin,
  promptSetChunk,
  promptSetCustom,
} from './prompt.js';
import { projectInfo, projectSetArtStyle, projectSetKey } from './project.js';
import { reportAgent, reportOpenIssue } from './report.js';
import {
  storyAssignLineIds,
  storyCoverage,
  storyDecomposeAll,
  storyDeleteLine,
  storyDeleteScene,
  storyExport,
  storyGraph,
  storyInsertLine,
  storyMergeScene,
  storyMoveLine,
  storyMoveShot,
  storyNewScene,
  storyPlay,
  storyRemoveChoice,
  storyScreenplay,
  storySetChoice,
  storySetCoverage,
  storySetHeading,
  storySetLineText,
  storySetNext,
  storySetOutfit,
  storySetSceneOutfit,
  storySetSpeaker,
  storySpliceScene,
  storySplitScene,
} from './story.js';
import { uploadFiles, uploadPick } from './upload.js';
import {
  viewApplyLayout,
  viewClose,
  viewFocus,
  viewLayout,
  viewLayouts,
  viewOpen,
  viewPalette,
  viewResetLayout,
  viewSaveLayout,
} from './view.js';
import { windowClose, windowNew, windowQuit } from './window.js';
import {
  workspaceChooseDirectory,
  workspaceCreate,
  workspaceDoctree,
  workspaceFiletree,
  workspaceImport,
  workspaceIndex,
  workspaceOpen,
  workspacePick,
  workspaceRecent,
  workspaceReindex,
} from './workspace.js';
import type { CommandHost } from './host.js';

export type { CommandHost } from './host.js';

export function createDesktopRegistry(): CommandRegistry<CommandHost> {
  const registry = new CommandRegistry<CommandHost>();
  registry.registerAll([
    agentClear,
    agentNewThread,
    agentOpenThread,
    agentRenameThread,
    agentRun,
    agentSetBudget,
    agentSetEffort,
    agentSetMode,
    agentSetModel,
    agentStop,
    agentThreads,
    artGenerate,
    artPromote,
    artRedraw,
    artSetNotes,
    artSetSeed,
    assetAccept,
    assetAdopt,
    assetInfo,
    assetRegenerate,
    assetReplace,
    assetSuspended,
    assetUpload,
    bibleSearch,
    commandCheck,
    docCreate,
    docRead,
    docRename,
    docWrite,
    gateApprove,
    gateCandidates,
    interactionList,
    interactionTargets,
    notifyClear,
    notifyDeleteAll,
    notifyFollow,
    notifyHide,
    notifyList,
    notifyMarkRead,
    notifyUnhide,
    pipelineRun,
    pipelineStatus,
    pipelineStop,
    promptAddRef,
    promptCheck,
    promptClear,
    promptCondense,
    promptDropRef,
    promptInfo,
    promptMoveChunk,
    promptRepin,
    promptSetChunk,
    promptSetCustom,
    projectInfo,
    projectSetArtStyle,
    projectSetKey,
    reportAgent,
    reportOpenIssue,
    storyAssignLineIds,
    storyCoverage,
    storyDecomposeAll,
    storyDeleteLine,
    storyDeleteScene,
    storyExport,
    storyGraph,
    storyInsertLine,
    storyMergeScene,
    storyMoveLine,
    storyMoveShot,
    storyNewScene,
    storyPlay,
    storyRemoveChoice,
    storyScreenplay,
    storySetChoice,
    storySetCoverage,
    storySetHeading,
    storySetLineText,
    storySetNext,
    storySetOutfit,
    storySetSceneOutfit,
    storySetSpeaker,
    storySpliceScene,
    storySplitScene,
    uploadFiles,
    uploadPick,
    viewApplyLayout,
    viewClose,
    viewFocus,
    viewLayout,
    viewLayouts,
    viewOpen,
    viewPalette,
    viewResetLayout,
    viewSaveLayout,
    windowClose,
    windowNew,
    windowQuit,
    workspaceChooseDirectory,
    workspaceCreate,
    workspaceDoctree,
    workspaceFiletree,
    workspaceImport,
    workspaceIndex,
    workspaceOpen,
    workspacePick,
    workspaceRecent,
    workspaceReindex,
  ]);
  return registry;
}
