/**
 * The story as commands: read the branch graph, rewire it, and write the prose.
 *
 * Every mutating command here follows the same path — a pure decision, then the one session
 * method that owns that write. A rewire is `branchops` + `session.editBranches`, which patches
 * the branch markers in whichever file each scene lives in — one `scenes/<id>.md` chunk, or the
 * whole screenplay. A prose edit is `lineops` + `session.editScene`, which re-serializes each
 * changed scene whole and can add or remove a chunk. Nothing else in the app writes either, so
 * one authorial act is one `CommandRecord` with one replayable invocation.
 *
 * The rewires, the prose edits, `setCoverage` and `assignLineIds` are `undoable`: they write
 * scene files and `work/shots/*.json`, which are documents. `story.export` and `story.screenplay`
 * are not — `story.play.json` and the projected screenplay are generated output, regenerated by
 * re-running the command.
 */
import {
  defineFor,
  prop,
  type CheckResult,
  type CommandContext,
  type CommandOutput,
} from '@vn/commands';
import {
  deleteLine,
  deleteScene,
  insertLine,
  mergeScene,
  moveLine,
  newScene,
  removeChoice,
  setChoice,
  setHeading,
  setLineText,
  setNext,
  setSpeaker,
  spliceScene,
  splitScene,
  type BranchOp,
  type LineOp,
  type SceneMap,
  type ScriptState,
} from '@vn/scriptedit';
import type { Scene } from '@vn/types';
import { setCoverage as decideCoverage } from '../../shared/coverage.js';
import { scenesOf } from '../../shared/interactions.js';
import type { CommandHost } from './host.js';

const define = defineFor<CommandHost>();

/** `-1` is the props layer's "absent": a command prop is optional only by having a default. */
const OPTIONAL_INDEX = -1;
const at = (index: number): number | undefined => (index < 0 ? undefined : index);

const idsOf = (lines: string): string[] =>
  lines
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);

/**
 * Apply a rewire, or refuse loudly — the stack turns a throw into `{ ok: false, error }`. The
 * decision sees the scenes whole: the rewires need only {@link SceneMap} and say so, but the outfit
 * marker is decided against a field that projection does not carry.
 */
async function apply(
  ctx: CommandContext<CommandHost>,
  decide: (scenes: Map<string, Scene>) => BranchOp,
): Promise<CommandOutput> {
  const result = await ctx.host.session.editBranches(decide);
  if (!result.ok) throw new Error(result.message);
  return { message: result.message, data: result.graph, written: result.written };
}

/**
 * The same decision `apply` would make, against a freshly read graph, and then discarded. It is
 * the rule itself rather than a description of it — the price is that the check reads the story
 * once more, which is what makes it a report about *now* rather than about the last load.
 */
async function preview(
  ctx: CommandContext<CommandHost>,
  decide: (scenes: SceneMap) => BranchOp,
): Promise<CheckResult> {
  const op = decide(scenesOf(await ctx.host.session.storyGraph()));
  return op.ok ? { ok: true, note: op.message } : { ok: false, reason: op.error };
}

/**
 * The `apply`/`preview` pair again, for prose. Deleted files — the chunk the edit ended, and a
 * storyboard that went with it — are reported in `written` beside the files that were written:
 * they are paths this command changed, which is what provenance and undo both want from that list.
 *
 * The preview runs the *whole* plan rather than just the decision, because the sentence worth
 * showing is the one about the shots: `previewSceneEdit` reads them and `editScene` rewrites them,
 * so the note a surface refuses or warns with is the note the run reports.
 */
async function edit(
  ctx: CommandContext<CommandHost>,
  decide: (state: ScriptState) => LineOp,
): Promise<CommandOutput> {
  const result = await ctx.host.session.editScene(decide);
  if (!result.ok) throw new Error(result.message);
  return {
    message: result.message,
    data: result.graph,
    written: [...result.written, ...result.removed],
  };
}

async function previewEdit(
  ctx: CommandContext<CommandHost>,
  decide: (state: ScriptState) => LineOp,
): Promise<CheckResult> {
  const preview = await ctx.host.session.previewSceneEdit(decide);
  return preview.ok ? { ok: true, note: preview.message } : { ok: false, reason: preview.message };
}

// The rewires whose props need shaping before `branchops` sees them build their decision here,
// so `check` and `run` are provably asking the same question.
const choiceOp =
  (scene: string, goto: string, label: string, index: number) =>
  (scenes: SceneMap): BranchOp => {
    const chosen = at(index);
    return setChoice(scenes, {
      scene,
      goto,
      label,
      ...(chosen !== undefined ? { index: chosen } : {}),
    });
  };

const spliceOp =
  (scene: string, from: string, edge: number) =>
  (scenes: SceneMap): BranchOp => {
    const chosen = at(edge);
    return spliceScene(scenes, { scene, from, ...(chosen !== undefined ? { edge: chosen } : {}) });
  };

export const storyGraph = define({
  id: 'story.graph',
  title: 'Story graph',
  description: 'Scenes, branch edges and reachability — what the branch editor draws.',
  mutating: false,
  props: {},
  async run(_props, ctx) {
    const graph = await ctx.host.session.storyGraph();
    const dead = graph.scenes.filter((s) => !s.reachable).length;
    return {
      message: `${graph.scenes.length} scene(s), ${graph.edges.length} edge(s), ${dead} unreachable.`,
      data: graph,
    };
  },
});

export const storySetChoice = define({
  id: 'story.setChoice',
  title: 'Set a choice',
  description: 'Add a branch choice to a scene, or replace the one at an index.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene the choice is offered in'),
    goto: prop.string('the scene it leads to'),
    label: prop.string('the decision text shown to the player'),
    index: prop.number('which choice to replace; omit to append a new one', {
      default: OPTIONAL_INDEX,
      min: OPTIONAL_INDEX,
    }),
  },
  check({ scene, goto, label, index }, ctx) {
    return preview(ctx, choiceOp(scene, goto, label, index));
  },
  run({ scene, goto, label, index }, ctx) {
    return apply(ctx, choiceOp(scene, goto, label, index));
  },
});

export const storyRemoveChoice = define({
  id: 'story.removeChoice',
  title: 'Remove a choice',
  description: "Delete one of a scene's branch choices by index.",
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to edit'),
    index: prop.number('which choice to remove', { min: 0 }),
  },
  check({ scene, index }, ctx) {
    return preview(ctx, (scenes) => removeChoice(scenes, { scene, index }));
  },
  run({ scene, index }, ctx) {
    return apply(ctx, (scenes) => removeChoice(scenes, { scene, index }));
  },
});

export const storySetNext = define({
  id: 'story.setNext',
  title: 'Set the next scene',
  description: "Set a scene's linear continuation, or clear it by passing an empty goto.",
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to edit'),
    goto: prop.string('the scene to continue to; empty clears the continuation', { default: '' }),
  },
  check({ scene, goto }, ctx) {
    return preview(ctx, (scenes) => setNext(scenes, { scene, goto }));
  },
  run({ scene, goto }, ctx) {
    return apply(ctx, (scenes) => setNext(scenes, { scene, goto }));
  },
});

export const storySpliceScene = define({
  id: 'story.spliceScene',
  title: 'Splice a scene into an edge',
  description: 'Rewire A→B into A→C→B in one patch. Refuses when C already forks.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to splice in (C)'),
    from: prop.string('the scene the edge leaves (A)'),
    edge: prop.number('which choice on `from`; omit for its next edge', {
      default: OPTIONAL_INDEX,
      min: OPTIONAL_INDEX,
    }),
  },
  check({ scene, from, edge }, ctx) {
    return preview(ctx, spliceOp(scene, from, edge));
  },
  run({ scene, from, edge }, ctx) {
    return apply(ctx, spliceOp(scene, from, edge));
  },
});

// The prose edits. Each is one authorial act, one `lineops` decision, one undo point — and each
// declares that decision as its `check`, so what a surface refuses is what a run would refuse.

const LINE_KINDS = [
  'dialogue',
  'parenthetical',
  'narration',
  'transition',
  'lyric',
  'centered',
] as const;

export const storySetLineText = define({
  id: 'story.setLineText',
  title: 'Retype a line',
  description:
    "Replace one line's text. The line id survives, so every shot covering it still does — but a " +
    'shot prompt never reads prose, so rendered art of this line drifts and will not re-render.',
  mutating: true,
  undoable: true,
  props: {
    line: prop.string('the line id, e.g. arrival:L3'),
    text: prop.string('what the line should say'),
  },
  check({ line, text }, ctx) {
    return previewEdit(ctx, (state) => setLineText(state, { line, text }));
  },
  run({ line, text }, ctx) {
    return edit(ctx, (state) => setLineText(state, { line, text }));
  },
});

export const storyInsertLine = define({
  id: 'story.insertLine',
  title: 'Insert a line',
  description:
    'Add a line after another, or at the top of the scene when `after` is omitted. The new line ' +
    "takes the scene's next allocated id, so no other line's coverage moves.",
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to insert into'),
    text: prop.string('what the line says'),
    after: prop.string('the line id to insert after; empty inserts at the top', { default: '' }),
    kind: prop.oneOf(LINE_KINDS, 'what sort of line it is', { default: 'dialogue' }),
    speaker: prop.string(
      'who says it; required for dialogue and parenthetical, refused otherwise',
      {
        default: '',
      },
    ),
  },
  check({ scene, text, after, kind, speaker }, ctx) {
    return previewEdit(ctx, (state) => insertLine(state, { scene, after, kind, speaker, text }));
  },
  run({ scene, text, after, kind, speaker }, ctx) {
    return edit(ctx, (state) => insertLine(state, { scene, after, kind, speaker, text }));
  },
});

export const storyDeleteLine = define({
  id: 'story.deleteLine',
  title: 'Delete a line',
  description:
    'Remove a line. Its id is retired and never reused, so a shot that covered it covers one ' +
    'line fewer — possibly none, which the timeline shows rather than treating as an error.',
  mutating: true,
  undoable: true,
  props: { line: prop.string('the line id to remove') },
  check({ line }, ctx) {
    return previewEdit(ctx, (state) => deleteLine(state, { line }));
  },
  run({ line }, ctx) {
    return edit(ctx, (state) => deleteLine(state, { line }));
  },
});

export const storyMoveLine = define({
  id: 'story.moveLine',
  title: 'Move a line',
  description:
    'Reorder a line within its scene. Ids do not change, so nothing detaches — but a shot was ' +
    'made to depict its covered lines in order, so art covering the moved line drifts.',
  mutating: true,
  undoable: true,
  props: {
    line: prop.string('the line id to move'),
    after: prop.string('the line id to sit after; empty moves it to the top', { default: '' }),
  },
  check({ line, after }, ctx) {
    return previewEdit(ctx, (state) => moveLine(state, { line, after }));
  },
  run({ line, after }, ctx) {
    return edit(ctx, (state) => moveLine(state, { line, after }));
  },
});

export const storySetSpeaker = define({
  id: 'story.setSpeaker',
  title: 'Set who speaks a line',
  description:
    'Change who speaks a line, or clear the speaker to make it narration. Attribution is the ' +
    'line kind, so this is also what turns narration into dialogue and back.',
  mutating: true,
  undoable: true,
  props: {
    line: prop.string('the line id to re-attribute'),
    speaker: prop.string('the character cue; empty makes the line narration', { default: '' }),
  },
  check({ line, speaker }, ctx) {
    return previewEdit(ctx, (state) => setSpeaker(state, { line, speaker }));
  },
  run({ line, speaker }, ctx) {
    return edit(ctx, (state) => setSpeaker(state, { line, speaker }));
  },
});

export const storyNewScene = define({
  id: 'story.newScene',
  title: 'New scene',
  description:
    'Create an empty scenes/<id>.md from a heading. Deliberately unwired: a new scene is ' +
    'unreachable until story.setNext or story.setChoice points at it.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene id, which is also its filename'),
    heading: prop.string('the Fountain heading, e.g. INT. CLASSROOM - EVENING'),
  },
  check({ scene, heading }, ctx) {
    return previewEdit(ctx, (state) => newScene(state, { scene, heading }));
  },
  run({ scene, heading }, ctx) {
    return edit(ctx, (state) => newScene(state, { scene, heading }));
  },
});

export const storySetHeading = define({
  id: 'story.setHeading',
  title: 'Set a scene’s heading',
  description:
    'Move a scene somewhere else by rewriting its Fountain heading. No line id changes, but the ' +
    'location is in every shot’s task inputs, so the scene’s rendered art is drawn again — the ' +
    'check says how much, and the prose it leaves behind is the agent’s to rewrite.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to move'),
    heading: prop.string('the new Fountain heading, e.g. EXT. ROOFTOP - NIGHT'),
  },
  check({ scene, heading }, ctx) {
    return previewEdit(ctx, (state) => setHeading(state, { scene, heading }));
  },
  run({ scene, heading }, ctx) {
    return edit(ctx, (state) => setHeading(state, { scene, heading }));
  },
});

export const storyDeleteScene = define({
  id: 'story.deleteScene',
  title: 'Delete a scene',
  description:
    'Remove a scene chunk, refusing while any choice, next edge or start: still points at it — ' +
    'the same failure a dangling goto would be, caught before it exists.',
  mutating: true,
  undoable: true,
  props: { scene: prop.string('the scene to remove') },
  check({ scene }, ctx) {
    return previewEdit(ctx, (state) => deleteScene(state, { scene }));
  },
  run({ scene }, ctx) {
    return edit(ctx, (state) => deleteScene(state, { scene }));
  },
});

export const storySplitScene = define({
  id: 'story.splitScene',
  title: 'Split a scene',
  description:
    'Cut a scene in two at a line: that line and everything below move into a new chunk the ' +
    'original continues to, and the branch out of the scene goes with the tail. Lines keep ' +
    'their local ids, so coverage can follow them.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to split'),
    at: prop.string('the line id that starts the second half'),
    into: prop.string('the id for the new second half'),
  },
  check({ scene, at, into }, ctx) {
    return previewEdit(ctx, (state) => splitScene(state, { scene, at, into }));
  },
  run({ scene, at, into }, ctx) {
    return edit(ctx, (state) => splitScene(state, { scene, at, into }));
  },
});

export const storyMergeScene = define({
  id: 'story.mergeScene',
  title: 'Merge a scene',
  description:
    'Absorb a scene into the one that continues to it, removing its chunk. Only across a linear ' +
    'continuation, and only when nothing else points at it. The absorbed lines are renumbered, ' +
    'so shots covering them stop covering anything.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to absorb'),
    into: prop.string('the scene that continues to it'),
  },
  check({ scene, into }, ctx) {
    return previewEdit(ctx, (state) => mergeScene(state, { scene, into }));
  },
  run({ scene, into }, ctx) {
    return edit(ctx, (state) => mergeScene(state, { scene, into }));
  },
});

export const storyCoverage = define({
  id: 'story.coverage',
  title: 'Scene coverage',
  description: "A scene's lines and the shots that cover them — what the timeline draws.",
  mutating: false,
  props: { scene: prop.string('the scene to read') },
  async run({ scene }, ctx) {
    const coverage = await ctx.host.session.sceneCoverage(scene);
    const covered = new Set(coverage.shots.flatMap((s) => s.coversLines));
    const gaps = coverage.lines.filter((l) => !covered.has(l.id)).length;
    return {
      message: coverage.decomposed
        ? `${coverage.shots.length} shot(s) over ${coverage.lines.length} line(s); ${gaps} uncovered.`
        : `${scene} has no decomposition yet.`,
      data: coverage,
    };
  },
});

export const storySetCoverage = define({
  id: 'story.setCoverage',
  title: 'Set shot coverage',
  description:
    'Set which lines a shot is on screen for. Claimed lines are taken off every other shot; ' +
    'released ones become visible gaps. Changes no prompt, so nothing rehashes.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene the shot belongs to'),
    shot: prop.string('the shot id, e.g. arrival__beat1'),
    lines: prop.string('comma-separated line ids; empty clears the shot', { default: '' }),
  },
  async check({ scene, shot, lines }, ctx) {
    const coverage = await ctx.host.session.sceneCoverage(scene);
    if (!coverage.decomposed) return { ok: false, reason: `${scene} has no decomposition yet.` };
    const op = decideCoverage(coverage.shots, {
      shot,
      lines: idsOf(lines),
      lineOrder: coverage.lines.map((l) => l.id),
    });
    return op.ok ? { ok: true, note: op.message } : { ok: false, reason: op.error };
  },
  async run({ scene, shot, lines }, ctx) {
    const ids = idsOf(lines);
    const result = await ctx.host.session.setCoverage(scene, shot, ids);
    if (!result.ok) throw new Error(result.message);
    return { message: result.message, data: result.coverage, written: result.written };
  },
});

export const storyMoveShot = define({
  id: 'story.moveShot',
  title: 'Move a shot',
  description:
    "Reorder a shot within its scene, which means moving the lines it covers. No shot's coverage " +
    'changes and no covered line changes or changes order within its own shot, so nothing drifts ' +
    'and nothing re-renders. A shot other shots draw inside is on screen in more than one place ' +
    'and has no single position, so it is refused by name.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene the shot belongs to'),
    shot: prop.string('the shot id to move, e.g. arrival__beat1'),
    after: prop.string('the shot id to sit after; empty moves it to the top', { default: '' }),
  },
  async check({ scene, shot, after }, ctx) {
    return previewEdit(ctx, await ctx.host.session.shotOrder(scene, shot, after));
  },
  async run({ scene, shot, after }, ctx) {
    return edit(ctx, await ctx.host.session.shotOrder(scene, shot, after));
  },
});

// The two outfit commands. Neither goes through `preview`: that decides against the story graph,
// which carries edges and reachability and not a word about clothes.

export const storySetSceneOutfit = define({
  id: 'story.setSceneOutfit',
  title: 'Dress a character for a scene',
  description:
    "Write a scene's [[outfit:]] marker for one character, or clear it with an empty outfit. It " +
    'applies to the whole scene wherever the marker sits, and every shot that does not override ' +
    'it re-renders in the new clothes.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to dress'),
    character: prop.string('the character id'),
    outfit: prop.string(
      "the outfit id; empty clears the marker and falls back to the character's",
      {
        default: '',
      },
    ),
  },
  async check({ scene, character, outfit }, ctx) {
    const op = await ctx.host.session.previewSceneOutfit(scene, character, outfit);
    return op.ok ? { ok: true, note: op.message } : { ok: false, reason: op.error };
  },
  async run({ scene, character, outfit }, ctx) {
    return apply(ctx, await ctx.host.session.sceneOutfit(scene, character, outfit));
  },
});

export const storySetOutfit = define({
  id: 'story.setOutfit',
  title: 'Dress a subject in a shot',
  description:
    "Override what one subject of one shot wears, or clear the override so the scene's marker — " +
    "or the character's default — reaches it again. Unlike coverage this changes the shot's " +
    'prompt, so the shot re-hashes and the next run re-renders it.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene the shot belongs to'),
    shot: prop.string('the shot id, e.g. arrival__beat1'),
    character: prop.string("which of the shot's subjects to dress"),
    outfit: prop.string('the outfit id; empty clears the override', { default: '' }),
  },
  async check({ scene, shot, character, outfit }, ctx) {
    const op = await ctx.host.session.previewShotOutfit(scene, shot, character, outfit);
    return op.ok ? { ok: true, note: op.message } : { ok: false, reason: op.error };
  },
  async run({ scene, shot, character, outfit }, ctx) {
    const result = await ctx.host.session.setShotOutfit(scene, shot, character, outfit);
    if (!result.ok) throw new Error(result.message);
    return { message: result.message, data: result.coverage, written: result.written };
  },
});

export const storyAssignLineIds = define({
  id: 'story.assignLineIds',
  title: 'Assign line ids',
  description:
    'Write the line ids reading already allocated into the scene files as [[line:]] marks, so ' +
    'inserting a line can no longer re-point the shots that cover the ones below it.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to mark; empty means every scene', { default: '' }),
  },
  async check({ scene }, ctx) {
    const preview = await ctx.host.session.previewLineIds(scene || undefined);
    return preview.ok
      ? { ok: true, note: preview.message }
      : { ok: false, reason: preview.message };
  },
  async run({ scene }, ctx) {
    const result = await ctx.host.session.writeLineIds(scene || undefined);
    if (!result.ok) throw new Error(result.message);
    return { message: result.message, written: result.written };
  },
});

export const storyDecomposeAll = define({
  id: 'story.decomposeAll',
  title: 'Storyboard every scene',
  description:
    'Ask the writing model for a storyboard for every reachable scene that has none yet, so the ' +
    'project can see the whole graph instead of one wave of it. One model call per scene, so it ' +
    'costs real money. A scene that already has one is left alone and there is no way to force ' +
    'it: the file wins forever, and re-decomposing would change shot ids, hence task identities, ' +
    'hence re-render art already paid for. A scene the model does not answer for is reported and ' +
    'NOT written, because an absent file is the only signal that means "decompose this". Run ' +
    'story.assignLineIds first, and write the cast sheets first — a character the project does ' +
    'not have yet is dropped from the shots silently and permanently.',
  mutating: true,
  // One undo point for the whole batch, which is the reason this is one command and not N.
  undoable: true,
  // A model call per scene, and the result is a file that wins forever. Both halves of that
  // deserve the dialog.
  confirm: true,
  props: {},
  async check(_props, ctx) {
    const state = await ctx.host.session.decomposePreconditions();
    // Mock or unresolved keys give the deterministic baseline for every scene, which
    // `decomposeAll` declines to write — so the run would be an expensive-looking no-op.
    if (state.keyError) return { ok: false, reason: state.keyError };
    if (state.pending.length === 0) {
      return { ok: false, reason: 'Every reachable scene already has a storyboard.' };
    }
    const bad = state.unreadable.length
      ? ` ${state.unreadable.length} file(s) will not parse.`
      : '';
    const risk = state.atRisk.length
      ? ` ${state.atRisk.join(', ')} name a character the project does not have — they will be dropped permanently.`
      : '';
    return { ok: true, note: `Would decompose ${state.pending.length} scene(s).${bad}${risk}` };
  },
  async run(_props, ctx) {
    const result = await ctx.host.session.decomposeAllScenes();
    const parts = [`Decomposed ${result.decomposed.length} scene(s)`];
    if (result.kept.length) parts.push(`${result.kept.length} already had one`);
    // Named, not counted: an unwritten scene is the one thing here an author has to act on.
    if (result.fellBack.length) {
      parts.push(`not written for ${result.fellBack.map((f) => f.scene).join(', ')}`);
    }
    if (result.unreadable.length) {
      parts.push(`unreadable: ${result.unreadable.map((u) => u.scene).join(', ')}`);
    }
    return {
      message: `${parts.join('; ')}.`,
      data: result,
      ...(result.decomposed.length ? { written: ['vngen/work/shots/'] } : {}),
    };
  },
});

export const storyPlay = define({
  id: 'story.play',
  title: 'Build playable',
  description: 'Project the model + asset store into the playable, in memory (no file written).',
  mutating: false,
  props: {},
  async run(_props, ctx) {
    const playable = await ctx.host.session.playable();
    return {
      message: `Playable built: ${Object.keys(playable.scenes).length} scene(s).`,
      data: playable,
    };
  },
});

export const storyExport = define({
  id: 'story.export',
  title: 'Export playable',
  description: 'Write vngen/build/story.play.json — the `vngen export` equivalent.',
  mutating: true,
  props: {},
  async check(_props, ctx) {
    // Building the playable *is* the question — it is pure and writes nothing, so the check
    // can answer with the real projection rather than a guess about whether one would work.
    const playable = await ctx.host.session.playable();
    const scenes = Object.keys(playable.scenes).length;
    return scenes
      ? { ok: true, note: `${scenes} scene(s) ready to export.` }
      : { ok: false, reason: 'There is no scene to export.' };
  },
  async run(_props, ctx) {
    const { scenes } = await ctx.host.session.exportPlayable();
    return {
      message: `Exported ${scenes} scene(s) to story.play.json.`,
      written: ['vngen/build/story.play.json'],
    };
  },
});

export const storyScreenplay = define({
  id: 'story.screenplay',
  // Named for the format it writes, beside `story.export`'s "Export playable". A menu entry
  // takes its tooltip from this title, so the two must be the same words.
  title: 'Export Fountain',
  description:
    'Project the scenes back into one Fountain screenplay at the project root — the `vngen ' +
    'screenplay` equivalent. A snapshot, not a mirror: it goes stale as soon as a scene changes.',
  mutating: true,
  props: {
    clean: prop.boolean('drop the [[…]] machine markers, which makes the output one-way', {
      default: false,
    }),
  },
  async check(_props, ctx) {
    const graph = await ctx.host.session.storyGraph();
    return graph.scenes.length
      ? { ok: true, note: `${graph.scenes.length} scene(s) ready to write.` }
      : { ok: false, reason: 'There is no scene to write.' };
  },
  async run({ clean }, ctx) {
    const result = await ctx.host.session.writeScreenplay(clean);
    if (!result.ok) throw new Error(result.message);
    return { message: result.message, written: result.written };
  },
});
