/**
 * The story's structure as commands: read the branch graph, and rewire it.
 *
 * Every mutating command here follows the same path — a pure `branchops` decision, then
 * `session.editBranches`, which patches the branch markers in whichever file each scene lives
 * in — one `scenes/<id>.md` chunk, or the whole screenplay — writes atomically and rebuilds the
 * model. Nothing else in the app writes branch wiring, so one authorial act is one
 * `CommandRecord` with one replayable invocation.
 *
 * The rewires, `setCoverage` and `assignLineIds` are `undoable`: they write scene prose and
 * `work/shots/*.json`, which are documents. `story.export` is not — `story.play.json` is
 * generated output, regenerated by re-running the command.
 */
import {
  defineFor,
  prop,
  type CheckResult,
  type CommandContext,
  type CommandOutput,
} from '@vn/commands';
import {
  removeChoice,
  setChoice,
  setNext,
  spliceScene,
  type BranchOp,
  type SceneMap,
} from '../../shared/branchops.js';
import { setCoverage as decideCoverage } from '../../shared/coverage.js';
import { scenesOf } from '../../shared/interactions.js';
import type { CommandHost } from './host.js';

const define = defineFor<CommandHost>();

/** `-1` is the props layer's "absent": a command prop is optional only by having a default. */
const OPTIONAL_INDEX = -1;
const at = (index: number): number | undefined => (index < 0 ? undefined : index);

const idsOf = (lines: string): string[] =>
  lines
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);

/** Apply a rewire, or refuse loudly — the stack turns a throw into `{ ok: false, error }`. */
async function apply(
  ctx: CommandContext<CommandHost>,
  decide: (scenes: SceneMap) => BranchOp,
): Promise<CommandOutput> {
  const result = await ctx.host.session.editBranches(decide);
  if (!result.ok) throw new Error(result.message);
  return { message: result.message, data: result.graph, written: result.written };
}

/**
 * The same decision `apply` would make, against a freshly read graph, and then discarded. It is
 * the rule itself rather than a description of it — the price is that the check reads the story
 * once more, which is what makes it a report about *now* rather than about the last load.
 */
async function preview(
  ctx: CommandContext<CommandHost>,
  decide: (scenes: SceneMap) => BranchOp,
): Promise<CheckResult> {
  const op = decide(scenesOf(await ctx.host.session.storyGraph()));
  return op.ok ? { ok: true, note: op.message } : { ok: false, reason: op.error };
}

// The rewires whose props need shaping before `branchops` sees them build their decision here,
// so `check` and `run` are provably asking the same question.
const choiceOp =
  (scene: string, goto: string, label: string, index: number) =>
  (scenes: SceneMap): BranchOp => {
    const chosen = at(index);
    return setChoice(scenes, {
      scene,
      goto,
      label,
      ...(chosen !== undefined ? { index: chosen } : {}),
    });
  };

const spliceOp =
  (scene: string, from: string, edge: number) =>
  (scenes: SceneMap): BranchOp => {
    const chosen = at(edge);
    return spliceScene(scenes, { scene, from, ...(chosen !== undefined ? { edge: chosen } : {}) });
  };

export const storyGraph = define({
  id: 'story.graph',
  title: 'Story graph',
  description: 'Scenes, branch edges and reachability — what the branch editor draws.',
  mutating: false,
  props: {},
  async run(_props, ctx) {
    const graph = await ctx.host.session.storyGraph();
    const dead = graph.scenes.filter((s) => !s.reachable).length;
    return {
      message: `${graph.scenes.length} scene(s), ${graph.edges.length} edge(s), ${dead} unreachable.`,
      data: graph,
    };
  },
});

export const storySetChoice = define({
  id: 'story.setChoice',
  title: 'Set a choice',
  description: 'Add a branch choice to a scene, or replace the one at an index.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene the choice is offered in'),
    goto: prop.string('the scene it leads to'),
    label: prop.string('the decision text shown to the player'),
    index: prop.number('which choice to replace; omit to append a new one', {
      default: OPTIONAL_INDEX,
      min: OPTIONAL_INDEX,
    }),
  },
  check({ scene, goto, label, index }, ctx) {
    return preview(ctx, choiceOp(scene, goto, label, index));
  },
  run({ scene, goto, label, index }, ctx) {
    return apply(ctx, choiceOp(scene, goto, label, index));
  },
});

export const storyRemoveChoice = define({
  id: 'story.removeChoice',
  title: 'Remove a choice',
  description: "Delete one of a scene's branch choices by index.",
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to edit'),
    index: prop.number('which choice to remove', { min: 0 }),
  },
  check({ scene, index }, ctx) {
    return preview(ctx, (scenes) => removeChoice(scenes, { scene, index }));
  },
  run({ scene, index }, ctx) {
    return apply(ctx, (scenes) => removeChoice(scenes, { scene, index }));
  },
});

export const storySetNext = define({
  id: 'story.setNext',
  title: 'Set the next scene',
  description: "Set a scene's linear continuation, or clear it by passing an empty goto.",
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to edit'),
    goto: prop.string('the scene to continue to; empty clears the continuation', { default: '' }),
  },
  check({ scene, goto }, ctx) {
    return preview(ctx, (scenes) => setNext(scenes, { scene, goto }));
  },
  run({ scene, goto }, ctx) {
    return apply(ctx, (scenes) => setNext(scenes, { scene, goto }));
  },
});

export const storySpliceScene = define({
  id: 'story.spliceScene',
  title: 'Splice a scene into an edge',
  description: 'Rewire A→B into A→C→B in one patch. Refuses when C already forks.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to splice in (C)'),
    from: prop.string('the scene the edge leaves (A)'),
    edge: prop.number('which choice on `from`; omit for its next edge', {
      default: OPTIONAL_INDEX,
      min: OPTIONAL_INDEX,
    }),
  },
  check({ scene, from, edge }, ctx) {
    return preview(ctx, spliceOp(scene, from, edge));
  },
  run({ scene, from, edge }, ctx) {
    return apply(ctx, spliceOp(scene, from, edge));
  },
});

export const storyCoverage = define({
  id: 'story.coverage',
  title: 'Scene coverage',
  description: "A scene's lines and the shots that cover them — what the timeline draws.",
  mutating: false,
  props: { scene: prop.string('the scene to read') },
  async run({ scene }, ctx) {
    const coverage = await ctx.host.session.sceneCoverage(scene);
    const covered = new Set(coverage.shots.flatMap((s) => s.coversLines));
    const gaps = coverage.lines.filter((l) => !covered.has(l.id)).length;
    return {
      message: coverage.decomposed
        ? `${coverage.shots.length} shot(s) over ${coverage.lines.length} line(s); ${gaps} uncovered.`
        : `${scene} has no decomposition yet.`,
      data: coverage,
    };
  },
});

export const storySetCoverage = define({
  id: 'story.setCoverage',
  title: 'Set shot coverage',
  description:
    'Set which lines a shot is on screen for. Claimed lines are taken off every other shot; ' +
    'released ones become visible gaps. Changes no prompt, so nothing rehashes.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene the shot belongs to'),
    shot: prop.string('the shot id, e.g. arrival__beat1'),
    lines: prop.string('comma-separated line ids; empty clears the shot', { default: '' }),
  },
  async check({ scene, shot, lines }, ctx) {
    const coverage = await ctx.host.session.sceneCoverage(scene);
    if (!coverage.decomposed) return { ok: false, reason: `${scene} has no decomposition yet.` };
    const op = decideCoverage(coverage.shots, {
      shot,
      lines: idsOf(lines),
      lineOrder: coverage.lines.map((l) => l.id),
    });
    return op.ok ? { ok: true, note: op.message } : { ok: false, reason: op.error };
  },
  async run({ scene, shot, lines }, ctx) {
    const ids = idsOf(lines);
    const result = await ctx.host.session.setCoverage(scene, shot, ids);
    if (!result.ok) throw new Error(result.message);
    return { message: result.message, data: result.coverage, written: result.written };
  },
});

export const storyAssignLineIds = define({
  id: 'story.assignLineIds',
  title: 'Assign line ids',
  description:
    'Write the line ids reading already allocated into the scene files as [[line:]] marks, so ' +
    'inserting a line can no longer re-point the shots that cover the ones below it.',
  mutating: true,
  undoable: true,
  props: {
    scene: prop.string('the scene to mark; empty means every scene', { default: '' }),
  },
  async check({ scene }, ctx) {
    const preview = await ctx.host.session.previewLineIds(scene || undefined);
    return preview.ok
      ? { ok: true, note: preview.message }
      : { ok: false, reason: preview.message };
  },
  async run({ scene }, ctx) {
    const result = await ctx.host.session.writeLineIds(scene || undefined);
    if (!result.ok) throw new Error(result.message);
    return { message: result.message, written: result.written };
  },
});

export const storyPlay = define({
  id: 'story.play',
  title: 'Build playable',
  description: 'Project the model + asset store into the playable, in memory (no file written).',
  mutating: false,
  props: {},
  async run(_props, ctx) {
    const playable = await ctx.host.session.playable();
    return {
      message: `Playable built: ${Object.keys(playable.scenes).length} scene(s).`,
      data: playable,
    };
  },
});

export const storyExport = define({
  id: 'story.export',
  title: 'Export playable',
  description: 'Write vngen/build/story.play.json — the `vngen export` equivalent.',
  mutating: true,
  props: {},
  async check(_props, ctx) {
    // Building the playable *is* the question — it is pure and writes nothing, so the check
    // can answer with the real projection rather than a guess about whether one would work.
    const playable = await ctx.host.session.playable();
    const scenes = Object.keys(playable.scenes).length;
    return scenes
      ? { ok: true, note: `${scenes} scene(s) ready to export.` }
      : { ok: false, reason: 'There is no scene to export.' };
  },
  async run(_props, ctx) {
    const { scenes } = await ctx.host.session.exportPlayable();
    return {
      message: `Exported ${scenes} scene(s) to story.play.json.`,
      written: ['vngen/build/story.play.json'],
    };
  },
});
