import {
  decideGenEdit,
  genNodeSpec,
  nodePropKeys,
  nodePropTarget,
  readGraphFile,
  registerGenNodes,
  type GenEdit,
  type GenEditDecision,
  type GenPropValue,
  type Graph,
  type Node as GenNode,
} from '@vn/gengraph';
import {
  Context,
  HotKey,
  KeyMap,
  NodeGraphView,
  PackFlags,
  UIBase,
  type Container,
  type ContextLike,
} from 'pathux';
import type { Button, DataAPI, EditVerdict, GraphEdit, NodeGraphDelegate } from 'pathux';
import type { ToolProperty } from 'pathux-toolprop';

import { api } from '../../api.js';
import {
  commandFor,
  contestedSlots,
  drawnSlot,
  genEditFor,
  noActiveOutput,
  setPropKey,
} from '../../rules/gengraph.js';
import GENGRAPH_CSS from '../../styles/gengraph.css?inline';
import { defineGraphApi } from '../api.js';
import { exec, onExec, onInvalidate, say } from '../bridge.js';
import { VnEditor, registerEditor } from '../editor.js';
import { assetNode, openNode } from '../open.js';
import type { VnScreen } from '../screen.js';

/**
 * The node graph one slot is generated by, drawn as a graph the author edits directly. Task Graph
 * says whether a slot has been drawn; this pane says how it will be.
 *
 * path.ux's view binds its widgets through the data API, and the editor gives it one rooted on the
 * graph on screen, so a node's prop rows and its unconnected inputs' editors are path.ux's own.
 * Every gesture is routed into a `gengraph.*` command by the delegate below, and every bound write
 * by the `change` listeners `subscribe` installs.
 */

/** What one gesture would do, weighed against the graph on screen with nothing written. */
type Weighed =
  | { ok: true; edit: GenEdit; decision: GenEditDecision }
  | { ok: false; reason: string };

/** One property the pane listens to, holding the value it last saw an edit accepted for. */
interface PropWatch {
  node: GenNode;
  key: string;
  target: ToolProperty;
  last: unknown;
  listener?: () => void;
}

export class GenGraphEditor extends VnEditor {
  private view!: NodeGraphView;
  private notesEl!: HTMLDivElement;
  private emptyEl!: HTMLDivElement;
  /** Opens the picture this graph drew. Repainted with the graph, since the slot moves with it. */
  private assetButton!: Button;

  /** The graph on screen, which trails `ui.graphSlug` by one read. */
  private graph: Graph | undefined;
  private slug = '';
  /** What the read and the file itself had to say. The graph's own notes are derived per paint. */
  private readNotes: string[] = [];
  /** Rising with every read, so a slow answer for a graph the pane has left is dropped. */
  private token = 0;

  /** The API the view binds through, kept so a refused write can be put back through it. */
  private graphApi!: DataAPI;
  private graphCtx!: ContextLike;
  private propWatches: PropWatch[] = [];
  /** True while a refusal is being written back, so the write does not read as an author's. */
  private reverting = false;

  /** The `gengraph.setProp` writes this pane has sent and has yet to hear an outcome for. */
  private sent = new Set<string>();
  /** Armed by this pane's own accepted write, and consumed by the reload that follows it. */
  private skipReload = false;

  static override define() {
    return {
      tagname: 'vn-gengraph-editor-x',
      areaname: 'gengraph',
      icon: -1,
    };
  }

  override init() {
    super.init();

    const bar = (this.header as Container).row();
    bar.label('GEN GRAPH').style['padding'] = '0px 8px';
    this.pinToggle(bar);
    describe(
      bar.button('Add…', () => this.view.openAddMenu(ADD_MENU_AT)),
      'Add a node to this graph',
    );
    describe(
      bar.button('Arrange', () => this.view.arrangeNodes()),
      'Lay the whole graph out again, left to right',
    );
    describe(
      bar.button('Delete', () => this.view.deleteSelected()),
      DELETE_WHAT,
    );
    this.assetButton = bar.button('Asset', () => void this.showAsset());
    describe(
      bar.button('⟳', () => void this.load(this.slug)),
      'Re-read this graph from disk',
    );
    bar.flushUpdate();

    this.adoptStyle(GENGRAPH_CSS);
    const surface = document.createElement('div');
    surface.className = 'gg-surface';

    this.notesEl = document.createElement('div');
    this.notesEl.className = 'gg-notes';
    surface.appendChild(this.notesEl);

    const canvas = document.createElement('div');
    canvas.className = 'gg-canvas';
    this.emptyEl = document.createElement('div');
    this.emptyEl.className = 'gg-empty';
    canvas.appendChild(this.emptyEl);
    surface.appendChild(canvas);
    this.appendSurface(surface);

    this.view = UIBase.createElement('nodegraphview-x') as NodeGraphView;
    // prevent sliders and textboxes from updating in realtime
    this.view.inherit_packflag |= PackFlags.NO_REALTIME;

    this.view.parentWidget = this.container;
    canvas.appendChild(this.view);
    // Per instance, because two Gen Graph panes may be open on different slugs and one `graph`
    // member cannot answer for both.
    this.graphApi = defineGraphApi(() => this.graph);
    this.graphCtx = (this.ctx as unknown as Context).override({
      api: this.graphApi,
    }) as unknown as ContextLike;
    this.view.ctx = this.graphCtx as unknown as typeof this.view.ctx;
    this.view._init();
    this.view.style.flex = '1 1 auto';
    this.view.style.minWidth = '0px';
    this.view.delegate = this.delegate();
    // path.ux opens its node menu from a right-click on a frame and offers none for the canvas
    // itself. A right-drag that panned has already had this event swallowed by the pan container.
    this.view.panzoom.addEventListener('contextmenu', (event: MouseEvent) => {
      event.preventDefault();
      const rect = this.view.panzoom.getBoundingClientRect();
      this.view.openAddMenu([event.clientX - rect.x, event.clientY - rect.y]);
    });

    // This keymap runs ahead of the screen keymap, and path.ux declines to route a keystroke that
    // landed in a textbox, so a node's own prop rows keep their editing keys.
    this.keymap = new KeyMap([
      new HotKey('Delete', [], () => this.view.deleteSelected(), DELETE_WHAT),
    ]);

    // The links are painted on a canvas sized from the pan area at paint time, and nothing repaints
    // it when the pane is dragged wider: they would stay clipped to the width the pane opened at.
    this.watch(() => {
      const observer = new ResizeObserver(() => this.view.syncGraph());
      observer.observe(this.view.panzoom);
      return () => observer.disconnect();
    });

    // `onInvalidate` is called with no arguments, so a listener cannot tell what moved the
    // project. The outcome can, and this fires immediately before the invalidation `exec` raises.
    this.watch(() =>
      onExec((id, outcome) => {
        if (id !== 'gengraph.setProp' || outcome.record === undefined) return;
        if (this.sent.delete(setPropKey(outcome.record.props)) && outcome.ok) {
          this.skipReload = true;
        }
      }),
    );

    // A command this pane sent is not the only thing that rewrites a graph: the agent's graph tool,
    // an undo and a `gengraph.*` invocation from the palette all reach the same file.
    this.watch(
      () =>
        onInvalidate(() => {
          // This pane's own write comes back as a whole-file reload under the widget being typed
          // into, and carries nothing new: main wrote the value `decideGenEdit` accepted here.
          // The strip still repaints, because standing the last output down changes what it says.
          if (this.skipReload) {
            this.skipReload = false;
            this.paintState();
          } else {
            void this.load(this.slug);
          }
        }),
      () => void this.load(this.slug),
    );

    this.paint();
  }

  override update() {
    super.update();

    const slug = this.ui.graphSlug;
    if (slug !== this.slug) void this.load(slug);
  }

  /** Drops the listeners with the pane, because path.ux detaches an editor on a tab switch. */
  override on_remove(): void {
    this.unsubscribe();
    super.on_remove();
  }

  // -------------------------------------------------------------------------
  // Reading
  // -------------------------------------------------------------------------

  private async load(slug: string): Promise<void> {
    const mine = ++this.token;
    this.slug = slug;

    if (slug === '') {
      this.graph = undefined;
      this.readNotes = [];
      this.paint();
      return;
    }

    const read = await api.invoke('gengraph:doc', slug);
    if (mine !== this.token) return;

    if (!read.ok) {
      this.graph = undefined;
      this.readNotes = [read.reason];
    } else {
      const parsed = readGraphFile(read.file);
      this.graph = parsed.graph;
      this.readNotes = [...parsed.diagnostics, ...read.diagnostics].map((note) => note.message);
    }
    this.paint();
  }

  /**
   * What the graph on screen says about itself. Derived rather than read, because a bound write
   * whose reload is skipped changes both of these without the file being read again.
   */
  private stateNotes(): string[] {
    if (this.graph === undefined) return [];

    const notes = contestedSlots(this.graph).map(
      (slot) => `More than one active output claims ${slot}, so no graph draws it.`,
    );
    if (noActiveOutput(this.graph)) {
      notes.push(
        'No output here is active, so this graph draws nothing and the slot falls back to ' +
          'the built-in runner.',
      );
    }
    return notes;
  }

  /**
   * Repaints what the graph says about itself — the strip above the canvas and the Asset button —
   * leaving the graph beneath it alone. Both answer to the same thing a bound write can change
   * without the file being read again: which output is active, and what slot it claims.
   */
  private paintState(): void {
    const notes = [...this.readNotes, ...this.stateNotes()];

    this.notesEl.textContent = notes.join('\n');
    this.notesEl.style.display = notes.length === 0 ? 'none' : 'block';

    const slot = this.graph === undefined ? '' : drawnSlot(this.graph);
    this.assetButton.disabled = slot === '';
    this.assetButton.description =
      slot === ''
        ? 'This graph names no one slot, so there is no picture of its own to show'
        : `Show what ${slot} holds in the Asset editor`;
  }

  /**
   * Opens whatever fills the slot this graph draws. The picture is read from the pipeline status
   * rather than carried on the graph: a graph says what it draws, and the store says what came of
   * it. An unsettled slot opens its first take, which is what the document tree heads it with.
   */
  private async showAsset(): Promise<void> {
    const slot = this.graph === undefined ? '' : drawnSlot(this.graph);
    if (slot === '') return;

    const status = await api.invoke('pipeline:status');
    const filled = status.slots.find((one) => one.key === slot);
    const hash = filled?.hash ?? filled?.candidates[0];
    if (hash === undefined) {
      say(`Nothing has been drawn for ${slot} yet, so there is no picture to show.`, true);
      return;
    }

    this.ui.assetHash = hash;
    this.announce();
    openNode(this.ctx?.screen as VnScreen | undefined, assetNode(hash));
  }

  /**
   * Points the view at what was read, keeping the selection across the reload. Every edit but a
   * property write reloads the whole file, so a selection dropped here would last one gesture.
   */
  private paint(): void {
    this.unsubscribe();

    const held = [...this.view.selection];
    this.view.setGraph(this.graph, 'graph');
    for (const id of held) {
      if (this.graph?.nodeIdMap.get(id) !== undefined) this.view.selection.add(id);
    }
    this.view.syncGraph();
    this.subscribe();

    this.paintState();
    this.emptyEl.textContent =
      this.slug === ''
        ? 'Pick a slot a generation graph draws to see the graph here.'
        : this.graph === undefined
          ? ''
          : this.graph.nodes.length === 0
            ? 'This graph has no nodes yet. Right-click the canvas to add one.'
            : '';
  }

  // -------------------------------------------------------------------------
  // Writing
  // -------------------------------------------------------------------------

  private delegate(): NodeGraphDelegate {
    return {
      check: (_ctx, edit): EditVerdict => this.judge(edit),
      perform: (_ctx, edit): void => this.dispatch(edit),
    };
  }

  /** Judges a gesture, and says the refusal that would otherwise leave a drop looking ignored. */
  private judge(edit: GraphEdit): EditVerdict {
    const weighed = this.weigh(edit);
    // A `moveNode` check runs once per frame per pointer move and shows its own refusal by fading
    // the frame, so speaking that one would repeat a sentence hundreds of times in a drag.
    if (!weighed.ok && edit.kind !== 'moveNode') say(weighed.reason, true);
    return weighed.ok ? { ok: true } : { ok: false, reason: weighed.reason };
  }

  private dispatch(edit: GraphEdit): void {
    const weighed = this.weigh(edit);
    if (!weighed.ok) return;
    // A drag is applied to the graph on screen as well as sent, because the view resyncs its frames
    // from `node.pos` the moment this returns and a frame that never moved snaps back.
    if (weighed.edit.op === 'moveNodes') weighed.decision.apply();
    this.send(weighed.edit);
  }

  private weigh(edit: GraphEdit): Weighed {
    const read = genEditFor(edit);
    if (!read.ok) return read;
    if (this.graph === undefined) return { ok: false, reason: 'no generation graph is open here' };

    const decision = decideGenEdit(this.graph, read.edit);
    return decision.ok
      ? { ok: true, edit: read.edit, decision }
      : { ok: false, reason: decision.reason };
  }

  /**
   * Sends one edit as the command that writes it. `exec` reloads this pane through its own hook,
   * except for the property writes noted here, which the watcher in `init` skips the reload for.
   */
  private send(edit: GenEdit): void {
    if (this.slug === '') return;
    const command = commandFor(this.slug, edit);
    if (edit.op === 'setProp') this.sent.add(setPropKey(command.props));
    void exec(command.id, command.props);
  }

  // -------------------------------------------------------------------------
  // The seam a bound widget writes through
  // -------------------------------------------------------------------------

  /**
   * Listens to every value the view draws a row for. `nodePropKeys` rather than `node.props` is
   * what reaches the socket rows: path.ux binds an unconnected input's default, and a frame admits
   * such a key only where the node declares no prop of that name.
   */
  private subscribe(): void {
    if (this.graph === undefined) return;

    for (const node of this.graph.nodes) {
      for (const key of nodePropKeys(node)) {
        const target = nodePropTarget(node, key);
        if (target === undefined) continue;

        const watch: PropWatch = { node, key, target, last: target.getValue() };
        watch.listener = () => this.onPropWrite(watch);
        target.on('change', watch.listener);
        this.propWatches.push(watch);
      }
    }
  }

  /**
   * Drops only what this pane added. A node registers a `change` listener of its own per property,
   * so clearing the callback list wholesale would break the node's own bookkeeping.
   */
  private unsubscribe(): void {
    for (const watch of this.propWatches) {
      if (watch.listener !== undefined) watch.target.off('change', watch.listener);
    }
    this.propWatches = [];
  }

  /**
   * Writes one bound edit, or puts the refused value back. `change` is a notification rather than
   * a veto — the property already holds the new value by the time this runs — so a refusal is
   * undone rather than prevented.
   */
  private onPropWrite(watch: PropWatch): void {
    if (this.reverting || this.graph === undefined) return;
    // A listener that outlived its graph by a frame would send a command for a node off screen.
    if (watch.node.graph !== this.graph) return;

    const value = genValue(watch.target.getValue());
    if (value === undefined || value === watch.last) return;

    const edit = editFor(watch.node, watch.key, value);
    const decision = decideGenEdit(this.graph, edit);
    if (!decision.ok) {
      say(decision.reason, true);
      this.revert(watch);
      return;
    }

    watch.last = value;
    this.send(edit);
  }

  /**
   * Puts the last accepted value back through the API the widget reads. A direct `setValue` on the
   * property would skip `notifyPathChange`, leaving the refused value on screen until the polling
   * fallback caught up.
   */
  private revert(watch: PropWatch): void {
    const path = `graph.nodes[${JSON.stringify(watch.node.id)}].props['${watch.key}'].value`;

    this.reverting = true;
    try {
      this.graphApi.setValue(this.graphCtx, path, watch.last);
    } finally {
      this.reverting = false;
    }
  }
}

/** Where the header's Add… menu opens, in the canvas's own coordinates. */
const ADD_MENU_AT: readonly [number, number] = [40, 40];

/** What deleting does, shared by the header button and the key that does the same thing. */
const DELETE_WHAT = 'Remove the selected nodes and sever the selected links';

function describe(button: { description?: string }, description: string): void {
  button.description = description;
}

/** The written value a property holds, or nothing where it holds something no command carries. */
function genValue(value: unknown): GenPropValue | undefined {
  const kind = typeof value;
  return kind === 'string' || kind === 'number' || kind === 'boolean'
    ? (value as GenPropValue)
    : undefined;
}

/**
 * The edit one write on a node's row is. Ticking `active` on an output stands the rivals claiming
 * its slot down at the same time, which is what `setActiveOutput` does; unticking has no such edit
 * behind it, so it is written as the plain property change the author asked for.
 */
function editFor(node: GenNode, key: string, value: GenPropValue): GenEdit {
  const slotProp = genNodeSpec(node.def.typeName)?.slotProp;
  if (slotProp !== undefined && key === 'active' && value === true) {
    return { op: 'setActiveOutput', node: node.id };
  }

  return { op: 'setProp', node: node.id, key, value };
}

// The registry is the renderer's own, so it is filled here rather than by the pane's first read.
registerGenNodes();

// The pane's subject is the shared selection, so it remembers only the pin `registerEditor` splices
// in from the `pins` field this editor declares.
registerEditor(GenGraphEditor, 'vn.GenGraphEditor');
