import {
  GroupNode,
  decideGenEdit,
  genNodeSpec,
  Node as GraphNode,
  instancedRefs,
  nodePropKeys,
  nodePropTarget,
  readGraphFile,
  readGroupFile,
  registerGenNodes,
  type GenEdit,
  type GenEditDecision,
  type GenPropValue,
  type Graph,
  type GraphId,
  type GroupDef,
  type Node as GenNode,
  type NodePropName,
} from '@vn/gengraph';
import {
  Context,
  KeyMap,
  NodeGraphView,
  PackFlags,
  UIBase,
  buildGroupDesigner,
  type Container,
  type ContextLike,
  type DescentEntry,
} from 'pathux';
import type { Button, DataAPI, EditVerdict, GraphEdit, NodeGraphDelegate } from 'pathux';
import type { ToolProperty } from 'pathux-toolprop';

import type { CheckpointHandle } from '../../../src/shared/ipc.js';
import {
  GRAPH_DOCS_DIR,
  graphDocPath,
  graphGroupPath,
  touches,
  touchesGraph,
} from '../../../src/shared/writes.js';
import { api } from '../../api.js';
import type { Offer } from '../../rules/anchors.js';
import {
  commandFor,
  contestedSlots,
  docPathFor,
  drawnSlot,
  genEditFor,
  newDocSync,
  noActiveOutput,
  reloadsOnAck,
  shouldReload,
  targetFor,
  type DocSync,
  type EditTarget,
} from '../../rules/gengraph.js';
import GENGRAPH_CSS from '../../styles/gengraph.css?inline';
import { defineGraphApi } from '../app/api.js';
import { beginCheckpoint, endCheckpoint, exec, onWrote, say } from '../app/bridge.js';
import { VnEditor, registerEditor } from '../app/editor.js';
import { redrawing } from '../tour/anchors.js';
import { assetNode, openNode } from '../panes/open.js';
import type { VnScreen } from '../app/screen.js';

/**
 * The node graph one slot is generated by, drawn as a graph the author edits directly. Task Graph
 * says whether a slot has been drawn; this pane says how it will be.
 *
 * path.ux's view binds its widgets through the data API, and the editor gives it one rooted on the
 * graph on screen, so a node's prop rows and its unconnected inputs' editors are path.ux's own.
 * Every gesture is routed into a `gengraph.*` command by the delegate below, and every bound write
 * by the `change` listeners `subscribe` installs.
 *
 * The view keeps a level: the root graph, a group's definition, or the inside of one instance.
 * Main never learns the level. An edit is addressed by what `targetFor` reads off the view's
 * descent — the definition file it goes to, and the instance prefix its node ids carry.
 */

/** What one gesture would do, weighed against the graph on screen with nothing written. */
type Weighed =
  { ok: true; edit: GenEdit; decision: GenEditDecision } | { ok: false; reason: string };

/** One property the pane listens to, holding the value it last saw an edit accepted for. */
interface PropWatch {
  node: GenNode;
  /** The graph the level was showing when the listener was installed. */
  level: Graph;
  /** How the level's graph names the node: its id, or `<instance>/<id>` for a forwarded row. */
  subject: string;
  /** The data path of the node, which a refusal writes the last accepted value back through. */
  path: string;
  key: NodePropName;
  target: ToolProperty;
  last: unknown;
  listener?: () => void;
}

/** Where a pane's layout put it in the graph, remembered with the graph it was in. */
interface HeldDescent {
  slug: string;
  descent: DescentEntry[];
}

export class GenGraphEditor extends VnEditor {
  private view!: NodeGraphView;
  private notesEl!: HTMLDivElement;
  private emptyEl!: HTMLDivElement;
  /** The group designer, shown at a definition level: its sockets and its forwarded rows. */
  private designerEl!: HTMLDivElement;
  /** Opens the picture this graph drew. Repainted with the graph, since the slot moves with it. */
  private assetButton!: Button;
  private groupButton!: Button;
  private ungroupButton!: Button;

  /** The graph on screen, which trails `ui.graphSlug` by one read. */
  private graph: Graph | undefined;
  private slug = '';
  /** The definitions the graph instances, learned when its groups resolved. */
  private refs: string[] = [];
  /** The node ids last anchored, so the frames are only re-recorded when the set of them changes. */
  private framed = ' ';
  /** The selection and level the group buttons were last drawn for. */
  private grouped = ' ';
  /** What the read and the file itself had to say. The graph's own notes are derived per paint. */
  private readNotes: string[] = [];
  /** Rising with every read, so a slow answer for a graph the pane has left is dropped. */
  private token = 0;

  /** The API the view binds through, kept so a refused write can be put back through it. */
  private graphApi!: DataAPI;
  private graphCtx!: ContextLike;
  private propWatches: PropWatch[] = [];
  /** True while a refusal is being written back, so the write does not read as an author's. */
  private reverting = false;

  /**
   * How far this pane's copy of each document has been carried, against everyone else's. Keyed by
   * the path an edit writes: the graph's own file, or a definition's.
   */
  private syncs = new Map<string, DocSync>();
  /** Told when the last outstanding write is answered; the group loader waits here. */
  private settling: (() => void)[] = [];

  /** Set for the span of one `singleUndoStep`, so `send` can tag its `exec` calls onto it. */
  private checkpoint: CheckpointHandle | undefined;

  /**
   * The level this pane was on when its layout was saved, as JSON, since a layout is read back
   * before any graph is. A struct field, so it is a public class field with a default.
   */
  descentJson = '';
  /** The saved level, held until the graph it was in has been read. */
  private heldDescent: HeldDescent | undefined;

  static override define() {
    return {
      tagname : 'vn-gengraph-editor-x',
      areaname: 'gengraph',
      icon    : -1,
    };
  }

  override init() {
    super.init();
    this.heldDescent = readDescent(this.descentJson);

    const bar = (this.header as Container).row();
    bar.label('GEN GRAPH').style['padding'] = '0px 8px';
    this.pinToggle(bar);
    describe(
      bar.button('Add…', () => this.view.openAddMenu(ADD_MENU_AT)),
      'Add a node to this graph',
    );
    describe(
      bar.button('Arrange', () => void this.view.arrangeNodes()),
      'Lay the whole graph out again, left to right',
    );
    describe(
      bar.button('Delete', () => void this.view.deleteSelected()),
      DELETE_WHAT,
    );
    describe(
      bar.button('Duplicate', () => void this.view.duplicateSelected()),
      DUPLICATE_WHAT,
    );
    // Wired by `paintGroupButtons`, which records what each would run against the selection.
    this.groupButton = bar.button('Group', () => {});
    this.ungroupButton = bar.button('Ungroup', () => {});
    this.assetButton = bar.button('Asset', () => void this.showAsset());
    describe(
      bar.button('⟳', () => void this.load(this.slug)),
      'Re-read this graph from disk',
    );
    bar.flushUpdate();

    this.adoptStyle(GENGRAPH_CSS);
    const surface = document.createElement('div');
    surface.className = 'gg-surface';

    this.notesEl = document.createElement('div');
    this.notesEl.className = 'gg-notes';
    surface.appendChild(this.notesEl);

    const canvas = document.createElement('div');
    canvas.className = 'gg-canvas';
    this.emptyEl = document.createElement('div');
    this.emptyEl.className = 'gg-empty';
    canvas.appendChild(this.emptyEl);
    surface.appendChild(canvas);
    this.appendSurface(surface);

    this.view = UIBase.createElement('nodegraphview-x') as NodeGraphView;
    // prevent sliders and textboxes from updating in realtime
    this.view.inherit_packflag |= PackFlags.NO_REALTIME;

    this.view.parentWidget = this.container;
    canvas.appendChild(this.view);
    this.designerEl = document.createElement('div');
    this.designerEl.className = 'gg-designer';
    this.designerEl.hidden = true;
    canvas.appendChild(this.designerEl);
    // Per instance, because two Gen Graph panes may be open on different slugs and one `graph`
    // member cannot answer for both.
    this.graphApi = defineGraphApi(() => this.graph);
    this.graphCtx = (this.ctx as unknown as Context).override({
      api: this.graphApi,
    }) as unknown as ContextLike;
    this.view.ctx = this.graphCtx as unknown as typeof this.view.ctx;
    this.view._init();
    this.view.style.flex = '1 1 auto';
    this.view.style.minWidth = '0px';
    this.view.delegate = this.delegate();
    // path.ux opens its node menu from a right-click on a frame and offers none for the canvas
    // itself. A right-drag that panned has already had this event swallowed by the pan container.
    this.view.panzoom.addEventListener('contextmenu', (event: MouseEvent) => {
      event.preventDefault();
      const rect = this.view.panzoom.getBoundingClientRect();
      this.view.openAddMenu([event.clientX - rect.x, event.clientY - rect.y]);
    });

    // The frames are rebuilt for every level, and the rows this pane listens to are the level's.
    this.view.addEventListener('levelchange', () => {
      if (this.heldDescent === undefined) {
        this.descentJson = JSON.stringify({ slug: this.slug, descent: this.view.descent });
      }
      this.framed = ' ';
      this.subscribe();
      this.paintDesigner();
      this.paintGroupButtons();
    });

    // The same list the example app installs, so the two cannot drift. This keymap runs ahead of
    // the screen keymap, and path.ux declines to route a keystroke that landed in a textbox, so a
    // node's own prop rows keep their editing keys.
    this.keymap = new KeyMap(this.view.hotkeys());

    // The links are painted on a canvas sized from the pan area at paint time, and nothing repaints
    // it when the pane is dragged wider: they would stay clipped to the width the pane opened at.
    this.watch(() => {
      const observer = new ResizeObserver(() => this.view.syncGraph());
      observer.observe(this.view.panzoom);
      return () => observer.disconnect();
    });

    // A command this pane sent is not the only thing that rewrites this graph's files: another
    // window, the agent's graph tool, a `gengraph.*` invocation from the palette and an undo all
    // reach them too. `onWrote` names the paths a write touched, so a write to some other document
    // is ignored rather than reloading this one, and the version it carries says whether this pane
    // has already been past the state being described. A definition file counts as this graph's
    // once the graph is known to instance it.
    this.watch(
      () =>
        onWrote((paths, versions) => {
          if (!touchesGraph(paths, this.slug, this.refs)) return;
          let reload = false;
          for (const path of this.trackedPaths()) {
            if (!touches(paths, path)) continue;
            const sync = this.syncFor(path);
            const version = versions[path];
            if (version !== undefined) sync.latest = Math.max(sync.latest, version);
            // A signal naming no version is an undo. While this pane has writes outstanding it is
            // passed over like every other echo, so it is noted for the write that settles them.
            else if (this.inflight() > 0) sync.stale = true;
            if (this.inflight() === 0 && shouldReload(sync, version)) reload = true;
          }
          if (reload) void this.load(this.slug);
          // Nothing new is on the file, but standing the last output down changes what the strip
          // above the canvas says about the graph, so that much is repainted.
          else this.paintState();
        }),
      () => void this.load(this.slug),
    );

    this.paint(false);
  }

  override update() {
    super.update();

    const slug = this.ui.graphSlug;
    if (slug !== this.slug) void this.load(slug);
    this.recordNodes();
    this.paintGroupButtons();
  }

  /**
   * One anchor per node frame, so a tour can point at the node it wants and the author can see
   * which one it means. A frame is a real element with its own pointer handlers, so this is the
   * plain DOM flavour rather than the canvas's.
   *
   * Re-recorded only when the set of frames changes. `syncGraph` reconciles frames by node id and
   * keeps the element across every other redraw, so the anchors stay pointing at live boxes.
   */
  private recordNodes(): void {
    const ids = [...this.view.frames.keys()].join(',');
    if (ids === this.framed) return;
    this.framed = ids;
    const nodes = redrawing('gengraph', 'nodes');
    for (const [id, frame] of this.view.frames) {
      nodes.item(frame, 'gnode', String(id), {});
    }
  }

  /** Drops the listeners with the pane, because path.ux detaches an editor on a tab switch. */
  override on_remove(): void {
    this.unsubscribe();
    super.on_remove();
  }

  // -------------------------------------------------------------------------
  // Groups
  // -------------------------------------------------------------------------

  /** Groups the selected nodes, or says what to select first. */
  async groupSelected(): Promise<void> {
    if (this.view.selection.size === 0) {
      say('Select the nodes to group first.', true);
      return;
    }
    await this.view.groupSelected();
  }

  /** Inlines every selected group instance, or says what to select first. */
  async ungroupSelected(): Promise<void> {
    if (this.selectedGroups().length === 0) {
      say('Select a group instance to ungroup.', true);
      return;
    }
    await this.view.ungroupSelected();
  }

  /** Opens the definition of the one selected group, or says what to select first. */
  enterGroup(): void {
    const groups = this.selectedGroups();
    if (groups.length !== 1) {
      say('Select one group to edit its definition.', true);
      return;
    }
    void this.view.enterDefinition(groups[0]!);
  }

  /** Leaves the current group for the one containing it. Reports when the graph is at its top. */
  exitGroup(): void {
    if (this.view.descent.length === 0) {
      say('This pane is already at the top of the graph.', true);
      return;
    }
    void this.view.exitLevel();
  }

  private selectedGroups(): GroupNode[] {
    const graph = this.view.currentGraph;
    const groups: GroupNode[] = [];
    for (const id of this.view.selection) {
      const node = graph?.nodeIdMap.get(id);
      if (node instanceof GroupNode) groups.push(node);
    }
    return groups;
  }

  /**
   * Records what Group and Ungroup would run against the selection, and says why either is
   * refused. Redrawn when the selection or the level changes, since the offer is theirs.
   */
  private paintGroupButtons(): void {
    const ids = [...this.view.selection];
    const signature = `${this.view.currentLevel().kind}|${ids.join(',')}|${this.slug}`;
    if (signature === this.grouped) return;
    this.grouped = signature;

    const pass = redrawing('gengraph', 'groups');
    const group = this.groupOffer(ids);
    pass.act(this.groupButton, group, () => void this.groupSelected());
    this.groupButton.disabled = !group.ok;
    this.groupButton.description = group.ok ? GROUP_WHAT : group.reason;

    const ungroup = this.ungroupOffer();
    pass.act(this.ungroupButton, ungroup, () => void this.ungroupSelected());
    this.ungroupButton.disabled = !ungroup.ok;
    this.ungroupButton.description = ungroup.ok ? UNGROUP_WHAT : ungroup.reason;
  }

  private groupOffer(ids: GraphId[]): Offer {
    const id = 'gengraph.createGroup';
    if (ids.length === 0) return { ok: false, id, reason: 'Select the nodes to group first.' };
    return this.offerOf(id, {
      kind     : 'createGroup',
      graphPath: this.view.currentGraphPath,
      storePath: this.view.graphPath,
      nodeIds  : ids,
    });
  }

  private ungroupOffer(): Offer {
    const id = 'gengraph.ungroup';
    const groups = this.selectedGroups();
    if (groups.length === 0) {
      return { ok: false, id, reason: 'Select a group instance to ungroup.' };
    }
    return this.offerOf(id, {
      kind     : 'ungroup',
      graphPath: this.view.currentGraphPath,
      nodeId   : groups[0]!.id,
    });
  }

  /** The invocation a gesture would send, weighed the way the delegate weighs it. */
  private offerOf(id: string, edit: GraphEdit): Offer {
    const target = this.target();
    const weighed = this.weigh(edit);
    if (!weighed.ok) return { ok: false, id, reason: weighed.reason };
    if (target === undefined) return { ok: false, id, reason: NO_LEVEL };
    return { ok: true, ...commandFor(target, weighed.edit) };
  }

  /** The designer follows the level: a definition's sockets and rows, and nothing elsewhere. */
  private paintDesigner(): void {
    const level = this.view.currentLevel();
    if (level.kind !== 'definition') {
      this.designerEl.hidden = true;
      this.designerEl.textContent = '';
      return;
    }

    this.designerEl.hidden = false;
    buildGroupDesigner(this.designerEl, {
      ctx       : this.view.graphContext,
      def       : level.def,
      graphPath : this.view.currentGraphPath,
      delegate  : this.view.delegate,
      onChanged : () => this.view.syncGraph(),
      errorColor: this.view.getDefault('ErrorColor') as string,
    });
  }

  /**
   * Serves a definition to the view's own resolve, once every write this pane has sent is
   * answered: the view's pass fires while a definition edit is still unacknowledged, and a load
   * then would hand back the old file. A definition that instances another resolves through the
   * same loader.
   */
  private groupLoader = async (ref: string): Promise<GroupDef | undefined> => {
    await this.settled();
    const read = await api.invoke('gengraph:group', ref);
    if (!read.ok) return undefined;
    const parsed = readGroupFile(read.file);
    if (parsed.def !== undefined) parsed.def.subgraph.groupLoader = this.groupLoader;
    return parsed.def;
  };

  // -------------------------------------------------------------------------
  // Reading
  // -------------------------------------------------------------------------

  /** Re-reads the graph; `select` is the node the reload is for, which the ack of an edit named. */
  private async load(slug: string, select?: GraphId): Promise<void> {
    const mine = ++this.token;
    const sameGraph = slug !== '' && slug === this.slug;
    this.slug = slug;
    // Versions count one graph's documents, so pointing the pane at another graph starts them
    // over. A write still outstanding against the graph being left is dropped with them: its
    // answer can no longer say anything about what is on screen.
    if (!sameGraph) this.syncs.clear();
    // This read is what puts the pane back on what the files hold, which is what being stale
    // meant, and at the latest version anyone has reported. Cleared as the read is issued rather
    // than when it lands, so a refusal arriving in between is still recorded.
    else {
      for (const sync of this.syncs.values()) {
        sync.stale = false;
        sync.mine = Math.max(sync.mine, sync.latest);
      }
    }

    if (slug === '') {
      this.graph = undefined;
      this.refs = [];
      this.readNotes = [];
      this.paint(false);
      return;
    }

    const read = await api.invoke('gengraph:doc', slug);
    if (mine !== this.token) return;

    if (!read.ok) {
      this.graph = undefined;
      this.refs = [];
      this.readNotes = [read.reason];
    } else {
      const parsed = readGraphFile(read.file);
      const graph = parsed.graph;
      // Main resolved the same instances and its diagnostics already say which failed; this
      // resolve gives the view definitions to enter and forwarded rows to draw.
      if (graph !== undefined) {
        graph.groupLoader = this.groupLoader;
        await graph.resolveGroups();
        if (mine !== this.token) return;
      }
      this.graph = graph;
      this.refs = graph === undefined ? [] : instancedRefs(graph);
      this.readNotes = [...parsed.diagnostics, ...read.diagnostics].map((note) => note.message);
    }
    this.paint(sameGraph);

    if (select !== undefined && this.view.currentGraph?.nodeIdMap.has(select)) {
      this.view.selection.clear();
      this.view.selection.add(select);
      this.view.syncGraph();
    }
  }

  /**
   * What the graph on screen says about itself. Derived rather than read, because a bound write
   * whose reload is skipped changes both of these without the file being read again.
   */
  private stateNotes(): string[] {
    if (this.graph === undefined) return [];

    const notes = contestedSlots(this.graph).map(
      (slot) => `More than one active output claims ${slot}, so no graph draws it.`,
    );
    if (noActiveOutput(this.graph)) {
      notes.push(
        'No output here is active, so this graph draws nothing and the slot falls back to ' +
          'the built-in runner.',
      );
    }
    return notes;
  }

  /**
   * Repaints what the graph says about itself — the strip above the canvas and the Asset button —
   * leaving the graph beneath it alone. Both answer to the same thing a bound write can change
   * without the file being read again: which output is active, and what slot it claims.
   */
  private paintState(): void {
    const notes = [...this.readNotes, ...this.stateNotes()];

    this.notesEl.textContent = notes.join('\n');
    this.notesEl.style.display = notes.length === 0 ? 'none' : 'block';

    const slot = this.graph === undefined ? '' : drawnSlot(this.graph);
    this.assetButton.disabled = slot === '';
    this.assetButton.description =
      slot === ''
        ? 'This graph names no one slot, so there is no picture of its own to show'
        : `Show what ${slot} holds in the Asset editor`;
  }

  /**
   * Opens whatever fills the slot this graph draws. The picture is read from the pipeline status
   * rather than carried on the graph: a graph says what it draws, and the store says what came of
   * it. An unsettled slot opens its first take, which is what the document tree heads it with.
   */
  private async showAsset(): Promise<void> {
    const slot = this.graph === undefined ? '' : drawnSlot(this.graph);
    if (slot === '') return;

    const status = await api.invoke('pipeline:status');
    const filled = status.slots.find((one) => one.key === slot);
    const hash = filled?.hash ?? filled?.candidates[0];
    if (hash === undefined) {
      say(`Nothing has been drawn for ${slot} yet, so there is no picture to show.`, true);
      return;
    }

    this.ui.assetHash = hash;
    this.announce();
    openNode(this.ctx?.screen as VnScreen | undefined, assetNode(hash));
  }

  /**
   * Points the view at what was read. `sameGraph` marks a reload of the file already on screen —
   * a reparse of the same slug — and uses `refreshGraph`, which keeps selection, descent and
   * pan/zoom, and reconciles frames by node id rather than tearing them all down. A genuine slug
   * change uses `setGraph`, which resets the view to the new graph's own state, and then puts the
   * pane back on the level its layout remembered.
   */
  private paint(sameGraph: boolean): void {
    if (sameGraph) {
      this.view.refreshGraph(this.graph);
    } else {
      this.view.setGraph(this.graph, 'graph');
      this.restoreDescent();
    }
    this.subscribe();

    this.paintState();
    this.paintDesigner();
    this.paintGroupButtons();
    this.emptyEl.textContent =
      this.slug === ''
        ? 'Pick a slot a generation graph draws to see the graph here.'
        : this.graph === undefined
          ? ''
          : this.graph.nodes.length === 0
            ? 'This graph has no nodes yet. Right-click the canvas to add one.'
            : '';
  }

  /** Applies the saved level once, to the graph it was saved in; any other graph drops it. */
  private restoreDescent(): void {
    const held = this.heldDescent;
    if (held === undefined || this.graph === undefined) return;
    this.heldDescent = undefined;
    if (held.slug !== this.slug || held.descent.length === 0) return;

    this.view.setViewState({ ...this.view.getViewState(), descent: held.descent });
  }

  // -------------------------------------------------------------------------
  // Writing
  // -------------------------------------------------------------------------

  /**
   * `undoStepBegin`/`undoStepEnd` bracket `deleteSelected`/`duplicateSelected`. This pane opens a
   * checkpoint there and closes it here, so every `gengraph.*` command the gesture dispatches
   * lands as one undo entry instead of one each; `send` tags its `exec` calls onto `this.checkpoint`
   * for the span. A refused open dispatches nothing, so `this.graph` is untouched by it; a refused
   * close can follow edits already applied optimistically to `this.graph`, so it forces a reload
   * the same way an ordinary refused write already does through `sync.stale`/`shouldReload`.
   */
  private delegate(): NodeGraphDelegate {
    return {
      undoStepBegin: async (_ctx, shortLabel, message): Promise<void> => {
        try {
          this.checkpoint = await beginCheckpoint(shortLabel, message, GRAPH_DOCS_DIR);
        } catch (err) {
          say(err instanceof Error ? err.message : String(err), true);
          throw err;
        }
      },
      check        : (_ctx, edit): EditVerdict => this.judge(edit),
      perform      : async (_ctx, edit): Promise<void> => this.dispatch(edit),
      undoStepEnd: async (): Promise<void> => {
        const checkpoint = this.checkpoint;
        this.checkpoint = undefined;
        if (checkpoint === undefined) return;

        const outcome = await endCheckpoint(checkpoint);
        if (!outcome.ok) {
          for (const sync of this.syncs.values()) sync.stale = true;
        }
        if (this.wantsReload()) void this.load(this.slug);
      },
    };
  }

  /** Judges a gesture, and says the refusal that would otherwise leave a drop looking ignored. */
  private judge(edit: GraphEdit): EditVerdict {
    const weighed = this.weigh(edit);
    // A `moveNode` check runs once per frame per pointer move and shows its own refusal by fading
    // the frame, so speaking that one would repeat a sentence hundreds of times in a drag.
    if (!weighed.ok && edit.kind !== 'moveNode') say(weighed.reason, true);
    return weighed.ok ? { ok: true } : { ok: false, reason: weighed.reason };
  }

  private dispatch(edit: GraphEdit): void {
    const target = this.target();
    const weighed = this.weigh(edit);
    if (!weighed.ok || target === undefined) return;

    // Main allocates a group's ref, and an instance is unresolved until a definition is loaded,
    // so these are sent first and shown when the acknowledgement reloads the graph.
    if (reloadsOnAck(weighed.edit.op)) {
      this.send(weighed.edit, target, true);
      return;
    }

    // Applied to the graph on screen as well as sent. The pane no longer re-reads the file when
    // its own write comes back, so whatever an edit does has to be done here or it is not shown
    // until something else forces a read. Both sides decide the edit with `decideGenEdit` against
    // the same file, and `Graph.add` takes ids from a counter the file itself carries, so a node
    // created here carries the id main writes for it.
    const applied = weighed.decision.apply();
    // A whole-DSL apply answers with a rebuilt graph rather than the one it was handed. Only the
    // root can be replaced that way; a level's graph is reached through the root.
    if (target.group === '' && target.prefix.length === 0) this.graph = applied.graph;

    // A drag needs no repaint: the view resyncs its frames from `node.pos` the moment this
    // returns. Every other edit changed which nodes, links or values exist, and only a repaint
    // puts that on screen — `refreshGraph` beneath it reconciles by node id, so the frames that
    // did not change are left alone.
    if (weighed.edit.op !== 'moveNodes') this.paint(true);

    this.send(weighed.edit, target);
  }

  private weigh(edit: GraphEdit): Weighed {
    const read = genEditFor(edit);
    if (!read.ok) return read;
    if (this.graph === undefined) return { ok: false, reason: 'no generation graph is open here' };
    const level = this.view.currentGraph;
    if (level === undefined) return { ok: false, reason: NO_LEVEL };

    const decision = decideGenEdit(level, read.edit);
    return decision.ok
      ? { ok: true, edit: read.edit, decision }
      : { ok: false, reason: decision.reason };
  }

  /** Where an edit at the level on screen is written, read off the view's descent. */
  private target(): EditTarget | undefined {
    return this.graph === undefined
      ? undefined
      : targetFor(this.slug, this.graph, this.view.descent);
  }

  /**
   * Sends one edit as the command that writes it. `reload` marks an edit the pane could not apply
   * itself, so the acknowledgement is what puts it on screen, with the node it created selected.
   */
  private send(edit: GenEdit, target: EditTarget, reload = false): void {
    if (this.slug === '') return;
    const command = commandFor(target, edit);
    const sync = this.syncFor(docPathFor(target));
    sync.inflight++;
    if (reload) sync.stale = true;
    void exec(command.id, command.props, this.checkpoint).then((outcome) => {
      sync.inflight--;
      if (outcome.ok) {
        // Every document the write produced a version of, the definition a group was created
        // under included, so the echo of this write is recognised on each of them.
        for (const [path, version] of Object.entries(outcome.versions ?? {})) {
          const own = this.syncFor(path);
          own.mine = Math.max(own.mine, version);
        }
      }
      // The edit was applied here before it was sent, so a refusal leaves the pane showing
      // something the file never took. `exec` has already said why; the way back is a read.
      else sync.stale = true;
      this.wake();
      // Every echo that arrived while this pane had writes outstanding was passed over, so a
      // change somebody else made during that window is picked up here or not at all.
      if (this.wantsReload()) {
        void this.load(this.slug, outcome.ok && reload ? createdNode(outcome.data) : undefined);
      }
    });
  }

  private syncFor(path: string): DocSync {
    let sync = this.syncs.get(path);
    if (sync === undefined) {
      sync = newDocSync();
      this.syncs.set(path, sync);
    }
    return sync;
  }

  /** The files this graph is read from: its own, and the definition of every group it instances. */
  private trackedPaths(): string[] {
    return this.slug === ''
      ? []
      : [graphDocPath(this.slug), ...this.refs.map((ref) => graphGroupPath(ref))];
  }

  private inflight(): number {
    let count = 0;
    for (const sync of this.syncs.values()) count += sync.inflight;
    return count;
  }

  /** Whether any document the pane has shown or written has moved past what it holds. */
  private wantsReload(): boolean {
    if (this.inflight() > 0) return false;
    for (const sync of this.syncs.values()) {
      if (shouldReload(sync, sync.latest)) return true;
    }
    return false;
  }

  /** Resolves once no write this pane sent is outstanding. */
  private settled(): Promise<void> {
    if (this.inflight() === 0) return Promise.resolve();
    return new Promise((resolve) => this.settling.push(resolve));
  }

  private wake(): void {
    if (this.inflight() > 0) return;
    const waiting = this.settling;
    this.settling = [];
    for (const resolve of waiting) resolve();
  }

  // -------------------------------------------------------------------------
  // The seam a bound widget writes through
  // -------------------------------------------------------------------------

  /**
   * Listens to every value the level draws a row for. `nodePropKeys` rather than `node.props` is
   * what reaches the socket rows: path.ux binds an unconnected input's default, and a frame admits
   * such a key only where the node declares no prop of that name. A group instance's frame draws
   * the rows its definition forwards, which bind an inner node of the instance's own copy, so
   * those are listened to under the instance's key.
   */
  private subscribe(): void {
    this.unsubscribe();
    const level = this.view.currentGraph;
    if (level === undefined) return;
    const levelPath = this.view.currentGraphPath;

    for (const node of level.nodes) {
      const path = `${levelPath}.nodes[${JSON.stringify(node.id)}]`;
      for (const key of nodePropKeys(node)) {
        this.listen(level, node, String(node.id), path, key);
      }
      if (!(node instanceof GroupNode) || node.definition === undefined) continue;

      for (const entry of node.definition.exposed) {
        const inner = node.subgraph.nodeIdMap.get(entry.nodeId);
        if (inner === undefined) continue;
        const innerPath = `${path}.group.nodes[${JSON.stringify(inner.id)}]`;
        const subject = `${String(node.id)}/${String(inner.id)}`;
        const keys = entry.kind === 'prop' ? [entry.propKey] : nodePropKeys(inner);
        for (const key of keys) this.listen(level, inner, subject, innerPath, key);
      }
    }
  }

  private listen(level: Graph, node: GenNode, subject: string, path: string, key: NodePropName) {
    if (this.propWatches.some((watch) => watch.node === node && watch.key === key)) return;
    const target = nodePropTarget(node, key);
    if (target === undefined) return;

    const watch: PropWatch = { node, level, subject, path, key, target, last: target.getValue() };
    watch.listener = () => this.onPropWrite(watch);
    target.on('change', watch.listener);
    this.propWatches.push(watch);
  }

  /**
   * Drops only what this pane added. A node registers a `change` listener of its own per property,
   * so clearing the callback list wholesale would break the node's own bookkeeping.
   */
  private unsubscribe(): void {
    for (const watch of this.propWatches) {
      if (watch.listener !== undefined) watch.target.off('change', watch.listener);
    }
    this.propWatches = [];
  }

  /**
   * Writes one bound edit, or puts the refused value back. `change` is a notification rather than
   * a veto — the property already holds the new value by the time this runs — so a refusal is
   * undone rather than prevented.
   */
  private onPropWrite(watch: PropWatch): void {
    if (this.reverting || this.graph === undefined) return;
    // A listener that outlived its level by a frame would send a command for a node off screen.
    if (watch.level !== this.view.currentGraph) return;
    const target = this.target();
    if (target === undefined) return;

    const value = genValue(watch.target.getValue());
    if (value === undefined || value === watch.last) return;

    const edit = editFor(watch, GraphNode.decomposePropName(watch.key).name, value);
    const decision = decideGenEdit(watch.level, edit);
    if (!decision.ok) {
      say(decision.reason, true);
      this.revert(watch);
      return;
    }

    watch.last = value;
    this.send(edit, target);
  }

  /**
   * Puts the last accepted value back through the API the widget reads. A direct `setValue` on the
   * property would skip `notifyPathChange`, leaving the refused value on screen until the polling
   * fallback caught up.
   */
  private revert(watch: PropWatch): void {
    const path = `${watch.path}.props['${watch.key}'].value`;

    this.reverting = true;
    try {
      this.graphApi.setValue(this.graphCtx, path, watch.last);
    } finally {
      this.reverting = false;
    }
  }
}

/** Where the header's Add… menu opens, in the canvas's own coordinates. */
const ADD_MENU_AT: readonly [number, number] = [40, 40];

/** What deleting does, shared by the header button and the key that does the same thing. */
const DELETE_WHAT = 'Remove the selected nodes and sever the selected links';

/** What duplicating does, shared by the header button and the key that does the same thing. */
const DUPLICATE_WHAT = 'Add a copy of each selected node, carrying over the values it authored';

const GROUP_WHAT =
  'Move the selected nodes into a new group, and leave an instance of it in their place (Ctrl+G)';

const UNGROUP_WHAT =
  'Put a copy of each selected group’s nodes where the instance stands, values included (Ctrl+Alt+G)';

/** Said where the view's level no longer resolves, which undo and delete can bring about. */
const NO_LEVEL = 'this level of the graph is no longer there; go back up';

function describe(button: { description?: string }, description: string): void {
  button.description = description;
}

/** The written value a property holds, or nothing where it holds something no command carries. */
function genValue(value: unknown): GenPropValue | undefined {
  const kind = typeof value;
  return kind === 'string' || kind === 'number' || kind === 'boolean'
    ? (value as GenPropValue)
    : undefined;
}

/**
 * The edit one write on a node's row is. Ticking `active` on an output stands the rivals claiming
 * its slot down at the same time, which is what `setActiveOutput` does; unticking has no such edit
 * behind it, so it is written as the plain property change the author asked for.
 */
function editFor(watch: PropWatch, key: string, value: GenPropValue): GenEdit {
  const slotProp = genNodeSpec(watch.node.def.typeName)?.slotProp;
  if (slotProp !== undefined && key === 'active' && value === true) {
    return { op: 'setActiveOutput', node: watch.node.id };
  }

  return { op: 'setProp', node: watch.subject, key, value };
}

/** The node an acknowledgement says the edit created, where it says one. */
function createdNode(data: unknown): GraphId | undefined {
  if (typeof data !== 'object' || data === null) return undefined;
  const node = (data as { node?: unknown }).node;
  return typeof node === 'string' || typeof node === 'number' ? node : undefined;
}

/** The level a layout remembered, or nothing for a layout from before levels or a bad string. */
function readDescent(text: string): HeldDescent | undefined {
  if (text === '') return undefined;
  try {
    const parsed = JSON.parse(text) as { slug?: unknown; descent?: unknown };
    if (typeof parsed.slug !== 'string' || !Array.isArray(parsed.descent)) return undefined;
    const descent: DescentEntry[] = [];
    for (const entry of parsed.descent as { nodeId?: unknown; into?: unknown }[]) {
      const id = entry.nodeId;
      if (typeof id !== 'string' && typeof id !== 'number') return undefined;
      descent.push({ nodeId: id, into: entry.into === 'definition' ? 'definition' : 'instance' });
    }
    return { slug: parsed.slug, descent };
  } catch {
    return undefined;
  }
}

// The registry is the renderer's own, so it is filled here rather than by the pane's first read.
registerGenNodes();

// The pane's subject is the shared selection, so it remembers only the pin `registerEditor` splices
// in from the `pins` field this editor declares, and the level it was on.
registerEditor(GenGraphEditor, 'vn.GenGraphEditor', ['descentJson : string']);
