/**
 * Core domain entities (report §3). Each entity is backed by a markdown/JSON file
 * on disk; these are the in-memory shapes the rest of the system manipulates.
 */
import type { PromptOverride } from './prompt.js';
import type { Transport } from './textmodels.js';

/** Lifecycle of a character's "look" through the approval gate (report §P3). */
export type CharacterStatus = 'draft' | 'candidates' | 'approved' | 'locked';

/**
 * Kinds of image assets (report §3, §7). The first five are the output of a planned task. A
 * `concept` is drawn on demand from a sentence, bound to what it sketches and consumed by nothing
 * (`docs/plans/archive/INDEX.md#on-demand-concept-images`). A `reference` is bytes the author brought in
 * from outside: generated by nothing and consumed by construction.
 */
export type AssetKind =
  | 'location_ref'
  | 'portrait'
  | 'model_sheet'
  | 'outfit_sheet'
  | 'shot_image'
  | 'concept'
  | 'reference';

/** A reference to a stored asset by its content hash. */
export interface AssetRef {
  /** sha256 content hash of the asset bytes. */
  hash: string;
  /** File extension without the dot, e.g. `png`. */
  ext: string;
}

/** Image-generation parameters that participate in the dedupe hash. */
export interface ImageParams {
  modelId: string;
  aspect?: string;
  seed?: number;
  /**
   * Extra params, hashed verbatim, so they carry task identity as well as anything a provider
   * reads. No provider reads any today; `sheet` is the key of the staging sheet a member shot is
   * drawn from, which re-keys the shot when the sheet's inputs move.
   */
  extra?: Record<string, string | number | boolean>;
}

/** A character outfit; the default outfit is produced by the model sheet (report §P4). */
export interface Outfit {
  id: string;
  /** Owning character id. */
  characterId: string;
  description: string;
  /** Art direction for this outfit alone — see {@link Character.artNotes}. */
  artNotes?: string;
  /** Image seed for this outfit's sheets — see {@link Character.seed}. */
  seed?: number;
  /** Image model for this outfit's sheets — see {@link Character.imageModel}. */
  imageModel?: string;
  /**
   * Override of this outfit's derived model-sheet prompt. The angle is recorded only on the task
   * and never on a rung, so one override covers all four angles of the sheet. The asset pane states that
   * coarseness rather than hiding it.
   */
  promptOverride?: PromptOverride;
  /** Model-sheet angle/expression images for this outfit, by label. */
  sheet?: Record<string, AssetRef>;
}

/** A character (report §3, §P3). */
export interface Character {
  id: string;
  name: string;
  /** Canonical, authoritative description fed to the LLM/image model. */
  description: string;
  traits: string[];
  /** Hex color palette injected into prompts for consistency. */
  palette: string[];
  status: CharacterStatus;
  /** Outfit id used when a shot does not specify one. */
  defaultOutfit: string;
  outfits: Outfit[];
  /**
   * Free-form art direction appended to every prompt this character reaches — how the picture
   * should look, as opposed to {@link description}, which is who the character is. Authored, so
   * an agent can set it; part of the prompt, so changing it re-keys the tasks it reaches and the
   * next run re-renders exactly those.
   */
  artNotes?: string;
  /**
   * The image seed every prompt this character reaches is drawn with, overriding
   * `config.image_params.seed`. In {@link ImageParams}, so it is in the task hash: setting one
   * re-keys what it reaches and the next run redraws exactly that. Changing the seed asks for a
   * different picture of the same words, which {@link artNotes} cannot express. `@vn/artgen`'s
   * `seedFor` is the only place the narrowest-rung-wins chain is written down.
   */
  seed?: number;
  /**
   * The image model every picture this character reaches is drawn with, in place of the
   * project's `models.image`. Not in the task hash — a rendered picture stays until it is
   * regenerated, and the next render uses this model. `@vn/artgen`'s `modelFor` resolves the
   * same narrowest-rung-wins chain `seedFor` does.
   */
  imageModel?: string;
  /**
   * Override of this character's derived portrait prompt, the one picture this rung names.
   * A sheet's override lives on its {@link Outfit}, which is the rung that names that picture.
   */
  promptOverride?: PromptOverride;
  /** Asset hash of the user-approved portrait, once the gate is passed. */
  approvedPortrait?: string;
}

/** A time-of-day / weather variant of a location (report §P1, §P2). */
export interface LocationVariant {
  /** e.g. `day`, `afternoon`, `night`, `rain`. */
  id: string;
  description: string;
  /** Art direction for this variant alone — see {@link Character.artNotes}. */
  artNotes?: string;
  /** Image seed for this variant's plate — see {@link Character.seed}. */
  seed?: number;
  /** Image model for this variant's plate — see {@link Character.imageModel}. */
  imageModel?: string;
  /** Override of this variant's derived plate prompt — the one picture this rung names. */
  promptOverride?: PromptOverride;
  /** Establishing/reference image once generated. */
  ref?: AssetRef;
}

/** A location (report §3, §P1). */
export interface Location {
  id: string;
  name: string;
  description: string;
  mood?: string;
  lighting?: string;
  palette: string[];
  variants: LocationVariant[];
  /** Art direction for every plate of this location — see {@link Character.artNotes}. */
  artNotes?: string;
  /** Image seed for every plate of this location — see {@link Character.seed}. */
  seed?: number;
  /** Image model for every plate of this location — see {@link Character.imageModel}. */
  imageModel?: string;
  /** True when mined from the screenplay rather than user-authored. */
  mined: boolean;
}

/** A branch edge from one scene to another (report §6). */
export interface Choice {
  label: string;
  goto: string;
}

/**
 * A single beat of a scene — one dialogue line, narration paragraph, parenthetical,
 * transition, lyric or centered line. Each carries a stable, scene-scoped id
 * (`${sceneId}:L<n>`) so shots can bind to exact lines and a runner can swap art per line.
 * Derived from the Fountain source at model-build time (report §P5.1); not persisted
 * independently.
 *
 * The local part is allocated rather than positional: `[[line: L4]]` in the source names it,
 * and an unmarked line takes the next id from {@link Scene.nextLineId}. Inserting a line
 * therefore leaves every other line's id alone.
 */
export interface SceneLine {
  /** Stable, scene-scoped id, e.g. `arrival:L3`. */
  id: string;
  /**
   * Every kind can be covered by a shot. Only `dialogue`/`parenthetical` are attributed.
   * Only `transition` produces no beat in the playable, because a transition is a cut rather
   * than something a reader is shown.
   */
  kind: 'dialogue' | 'parenthetical' | 'narration' | 'transition' | 'lyric' | 'centered';
  /** Speaker character id; present for `dialogue`/`parenthetical` and nothing else. */
  speaker?: string;
  text: string;
}

/**
 * The interior/exterior prefix a scene heading opens with, normalized to its canonical
 * spelling. Absent for a forced (`.HEADING`) heading, which has no prefix to keep.
 */
export type HeadingPrefix = 'INT.' | 'EXT.' | 'INT./EXT.' | 'EST.' | 'I/E';

/**
 * Whether a shot's rendered frame still illustrates the words it covers. Derived on every read
 * by `@vn/pipeline`'s `driftOf` and never persisted — a stored flag can be stale, a hash cannot.
 * The shape lives here because the timeline, the task list and the inspector all name it.
 */
export type Drift =
  /** No image yet, so there is nothing that could be stale. */
  | 'unrendered'
  /** The recorded prose hash matches: this frame was made from these words. */
  | 'current'
  /** The recorded prose hash does not match. The frame stands until something asks for a redraw. */
  | 'drifted'
  /** Rendered before {@link Shot.proseHash} existed, so drift cannot be determined. */
  | 'unknown';

/** A rectangle in page fractions, `x`/`y` its top-left corner. */
export interface PanelBox {
  x: number;
  y: number;
  w: number;
  h: number;
}

/**
 * One panel of a page shot. A shot with panels renders one picture, the whole page, and each
 * panel is a region of it with its own framing, camera and cast; outfits come from the parent
 * shot's cast, so a character wears one outfit across the page.
 */
/**
 * A speech bubble the runner draws over a page under `lettering: runner`. Authored on the panel
 * that letters the line, in page fractions; not in the prompt, so placing one re-renders nothing.
 */
export interface PanelBubble {
  /** One of the parent panel's {@link PagePanel.coversLines}; a line has at most one bubble. */
  lineId: string;
  /** Where the bubble sits. */
  anchor: [number, number];
  /** Where the tail points, at the speaker. Absent draws a caption box with no tail. */
  tail?: [number, number];
  /**
   * Whether the speaker's name is shown above the line, in place of the project's
   * `bubble_names`. Absent inherits it. Read only for a dialogue line; narration has no name.
   */
  name?: boolean;
}

export interface PagePanel {
  /** The panel's outline in page fractions, clockwise, at least three points. */
  shape: [number, number][];
  framing: Shot['framing'];
  camera?: string;
  /**
   * Who is in this panel, with the pose and expression they hold there. Each must be in the
   * parent shot's {@link Shot.subjects}; the store refuses a panel naming anyone else.
   */
  subjects: { characterId: string; pose?: string; expression?: string }[];
  /** A partition of the parent shot's {@link Shot.coversLines}: the lines lettered here. */
  coversLines: string[];
  /** Art direction for this panel alone, appended to the panel's own sentence. */
  artNotes?: string;
  /** The bubbles the runner draws for this panel's lines. Absent or empty means none is placed. */
  bubbles?: PanelBubble[];
}

/** A single rendered image within a scene (report §3, §P5). */
export interface Shot {
  id: string;
  /** Parent scene id. */
  sceneId: string;
  framing: 'wide' | 'medium' | 'close' | 'establishing';
  /** Location variant id this shot is set in. */
  location: string;
  subjects: ShotSubject[];
  /**
   * Whether {@link subjects} are carried as references rather than as a casting instruction. The
   * reviewer is then told nothing has to be in frame, so a subject the image leaves out is no
   * longer a blocking defect and the refine loop stops burning attempts on it. Absent means the
   * subjects must appear, which is what every shot a decomposer wrote means.
   */
  castOptional?: boolean;
  camera?: string;
  /** Art direction for this frame alone — see {@link Character.artNotes}. Authored, like
   * {@link camera}, and in the prompt, so editing it re-renders this shot and nothing else. */
  artNotes?: string;
  /** Image seed for this frame alone — see {@link Character.seed}. Authored, like {@link artNotes}. */
  seed?: number;
  /** Image model for this frame alone — see {@link Character.imageModel}. */
  imageModel?: string;
  /**
   * Aspect ratio for this frame alone, such as `3:4`, in place of `image_params.aspect`. Authored,
   * like {@link seed}, and in the task's params, so setting it re-renders this shot and nothing
   * else.
   */
  aspect?: string;
  /**
   * The panels of a page shot. Absent means a single frame, which is what every shot was before
   * pages existed. Authored, and in the prompt: the page's layout, each panel's cast and (under
   * `lettering: model`) the lines it letters are all derived from this list, so editing it
   * re-renders the page.
   */
  panels?: PagePanel[];
  /**
   * The staging-sheet group this shot is drawn from, one of its scene's {@link Scene.sheets} keys.
   * Authored, and in the task's params through the sheet's key, so moving a shot between groups
   * re-renders it.
   */
  sheet?: string;
  /** Override of this frame's derived prompt. Authored, like {@link artNotes}. */
  promptOverride?: PromptOverride;
  /** Dialogue line ids this shot covers. */
  coversLines: string[];
  /** Filled in P6. */
  prompt?: string;
  /** Asset hash, filled in P7. */
  image?: string;
  /**
   * Hash of the text of the lines this shot covered at the moment {@link image} was produced.
   * A shot has drifted when that disagrees with the same hash computed from the scene now; see
   * `@vn/pipeline`'s `driftOf`. Absent on a shot rendered before the field existed, which
   * reads as unknown and never as drifted.
   */
  proseHash?: string;
  /**
   * The panel boxes a reviewer saw in {@link image}, in reading order. Derived and recorded
   * beside the image, like {@link proseHash}; the intended geometry stays in {@link panels}, and
   * nothing downstream reads these. Absent on a frame, on an unrendered page, and on a page no
   * reviewer measured.
   */
  panelBoxes?: PanelBox[];
  status: 'pending' | 'prompted' | 'generated' | 'accepted' | 'needs_human';
}

/** A subject (character + outfit + pose/expression) appearing in a shot. */
export interface ShotSubject {
  characterId: string;
  /**
   * This shot's own outfit override. Absent means inherit, first from the scene's `[[outfit:]]`
   * marker and then from the character's default, so the decomposer deliberately leaves it unset.
   * `@vn/model`'s `outfitFor` is the only place that chain is written down.
   */
  outfit?: string;
  pose?: string;
  expression?: string;
}

/** A scene, which is one node of the branch graph (report §6). */
export interface Scene {
  id: string;
  /** Location id (not variant) the scene takes place in. */
  location: string;
  /**
   * Time-of-day variant the heading named (the `AFTERNOON` of `INT. GATE - AFTERNOON`), slugged.
   * The location plate is generated from this variant, so losing it changes the art.
   */
  locationVariant?: string;
  /** The heading's interior/exterior prefix; absent when the heading was forced with `.`. */
  headingPrefix?: HeadingPrefix;
  characters: string[];
  /**
   * Outfits the scene puts its cast in, character id → outfit id, from `[[outfit: aiko=uniform]]`
   * markers. Scene-scoped wherever the marker sits: a mid-scene change of clothes is a shot-level
   * override or a scene split, never a position in {@link lines}.
   */
  outfits?: Record<string, string>;
  /** Concise beat/synopsis for the LLM. */
  synopsis?: string;
  /**
   * The scene's prose as structured, ordered lines — the single representation of what the
   * scene says. Shots bind to it (via {@link Shot.coversLines}), the runner replays it, and
   * `sceneToFountain` writes it back out. Regenerated each model build.
   */
  lines: SceneLine[];
  /**
   * Monotonic high-water mark for this scene's line-id allocator — the next local id to
   * hand out. Read from `[[nextline: n]]` when present, otherwise derived as
   * `max(allocated) + 1`. Retired ids are never reused, so it only ever rises.
   */
  nextLineId?: number;
  /** Branch edges; empty for a leaf. */
  choices: Choice[];
  /** Linear continuation when there are no explicit choices. */
  next?: string;
  shots: Shot[];
  /**
   * The scene's staging-sheet groups by id, from the shots file. A shot's {@link Shot.sheet} names
   * one; a group a shot names but this map lacks takes the defaults. Absent until a shot names one.
   */
  sheets?: Record<string, SheetGroup>;
}

/** The most cells one staging sheet carries; a longer group is the author's to split. */
export const MAX_SHEET_CELLS = 8;

/** One staging-sheet group's own settings: the seed the whole sheet is drawn with, and notes. */
export interface SheetGroup {
  /** Rerolling the sheet is bumping this, which re-keys every member shot at once. */
  seed?: number;
  /** Words about the group for the sheet prompt, such as what stays fixed across it. */
  notes?: string;
}

/** The entity, scene or shot an asset serves. */
export interface AssetBinding {
  characterId?: string;
  outfit?: string;
  /**
   * Which of an outfit's sheets this is. On a binding written since takes were held; a sheet row
   * without one is told apart from its siblings through its task's inputs instead.
   */
  angle?: string;
  locationId?: string;
  variant?: string;
  sceneId?: string;
  shotId?: string;
}

/**
 * How a take's bytes entered its slot. Stamped on the row by the first hold and kept by every
 * later one, so a restore leaves it alone and records itself on the attempt instead.
 */
export type TakeVia = 'run' | 'graph' | 'adopt' | 'promote' | 'upload' | 'migrated';

/** What a hold stamps on the row it holds. */
export interface TakeStamp {
  /** ISO timestamp of the hold. */
  at?: string;
  via?: TakeVia;
}

/**
 * What the one-shot migration writes onto a row: the take bits, and for a sheet the angle
 * backfilled onto its outfit binding.
 */
export interface TakeEdit extends TakeStamp {
  current: boolean;
  angle?: string;
}

/** A stored, generated image and its provenance (report §3, §8). */
export interface Asset {
  hash: string;
  ext: string;
  kind: AssetKind;
  /** Task hash that produced it. */
  sourceTask: string;
  prompt?: string;
  /** Reference asset hashes fed into the generation, in order. */
  refs: string[];
  /** The model as `project.yaml` or the node named it, never its OpenRouter spelling. */
  modelId: string;
  /**
   * Which key carried the call. Absent on a record written before routing existed, and then
   * read as the model's own vendor.
   */
  transport?: Transport;
  params?: ImageParams;
  /**
   * Everything this asset satisfies, for the manifest index. A list because bytes are keyed by
   * content: two tasks that produce the same image share one record, and the second binding
   * must not erase the first. A manifest written with a single record reads as one element.
   */
  satisfies: AssetBinding[];
  /**
   * Whether these are the bytes the slot holds. At most one row per slot; a hold clears the
   * others in the same write. Absent on a row written before takes were held, which every reader
   * treats as false and `migrateCurrent` stamps once.
   */
  current?: boolean;
  /**
   * Whether a person approved this take. Never cleared by a hold, so a superseded take keeps it
   * as history; a surface asking "is this approved" reads `current` as well.
   */
  accepted: boolean;
  /** ISO timestamp of the last hold — when the slot most recently took these bytes. */
  at?: string;
  /** See {@link TakeVia}. */
  via?: TakeVia;
  /**
   * A short human name, for an asset whose name cannot be derived from what it serves. A plate's
   * binding gives it the name "Café Mori — night"; a concept was asked for in a sentence, and that
   * sentence is its only name.
   */
  title?: string;
}

/**
 * Whether `asset` serves everything `binding` names — one place to ask, so the surfaces don't
 * each spell the list traversal differently. An empty `binding` matches any bound asset.
 */
export function bindsTo(asset: Asset, binding: AssetBinding): boolean {
  const wanted = Object.entries(binding).filter(([, v]) => v !== undefined);
  return asset.satisfies.some((b) => wanted.every(([k, v]) => b[k as keyof AssetBinding] === v));
}
