/**
 * Pure builders for the two generated command-reference files, shared by
 * `gen-command-table.mjs` (writes them) and `check-command-table.mjs` (only compares).
 */
const HEADER = '<!-- generated by scripts/gen-command-table.mjs; do not edit by hand -->';
const LEGEND = '✍ mutating ⚠ confirm ↺ undoable ✓ declares a precondition';

function escapeCell(text) {
  return text.replace(/\|/g, '\\|');
}

function symbols(entry) {
  let s = '';
  if (entry.mutating) s += ' ✍';
  if (entry.confirm) s += ' ⚠';
  if (entry.undoable) s += ' ↺';
  if (entry.checkable) s += ' ✓';
  return s;
}

function formatDefault(value) {
  return typeof value === 'string' ? `\`'${value}'\`` : `\`${value}\``;
}

function formatProp(prop) {
  let s = `\`${prop.name}\``;
  if (prop.kind === 'secret') {
    s += ' (**secret**)';
  } else if (prop.digest) {
    s += ' (digest)';
  } else if (prop.kind === 'enum' && prop.values) {
    const values = prop.values.map((v) => `\`${v}\``).join('\\|');
    s +=
      prop.default !== undefined
        ? ` (${values}, default ${formatDefault(prop.default)})`
        : ` (${values})`;
  } else if (prop.default !== undefined) {
    s += ` (default ${formatDefault(prop.default)})`;
  }
  return s;
}

function formatProps(props) {
  return props.length > 0 ? props.map(formatProp).join(', ') : '—';
}

function row(entry) {
  const command = `\`${entry.id}\`${symbols(entry)}`;
  const props = formatProps(entry.props);
  const notes = entry.notes ? escapeCell(entry.notes) : '—';
  return `| ${command} | ${props} | ${notes} |`;
}

function table(entries) {
  return ['| Command | Props | Notes |', '| ------- | ----- | ----- |', ...entries.map(row)].join(
    '\n',
  );
}

/** Builds both files' contents from a `DocCommandEntry[]`. Writes nothing. */
export function buildCommandTables(entries) {
  const namespaces = [...new Set(entries.map((e) => e.namespace))];
  const counts = {
    total     : entries.length,
    namespaces: namespaces.length,
    mutating  : entries.filter((e) => e.mutating).length,
    checkable : entries.filter((e) => e.checkable).length,
    undoable  : entries.filter((e) => e.undoable).length,
    confirm   : entries.filter((e) => e.confirm).length,
  };

  const flatFile = `${HEADER}

# Registered commands

${counts.total} commands, in ${counts.namespaces} namespaces. ${counts.mutating} are \`mutating\`;
${counts.checkable} declare a precondition; ${counts.undoable} are undoable; ${counts.confirm} ask
for confirmation.

${LEGEND}

${table(entries)}
`;

  const namespaceFile = `${HEADER}

# Commands by namespace

${namespaces
  .map((ns) => {
    const nsEntries = entries.filter((e) => e.namespace === ns);
    return `## \`${ns}.\`\n\n${table(nsEntries)}`;
  })
  .join('\n\n')}
`;

  return { flatFile, namespaceFile };
}
