/**
 * Installing the GitHub Pages publisher into an author's project repo.
 *
 * Two files land in the project: a workflow GitHub reads, and a self-contained copy of the site
 * renderer for that workflow to run. The renderer is committed rather than installed because
 * every package in this monorepo is `private: true` — there is no `npx vngen` for a runner to
 * reach, so the code has to travel with the project. `scripts/esbuild.sitebuilder.mjs` bundles it
 * with no externals for exactly that reason: CI does no install and the project has no
 * `node_modules`.
 *
 * The workflow force-pushes an orphan `gh-pages` branch rather than deploying to Pages directly,
 * so what is published is a branch the author can open and read.
 */
import { existsSync } from 'node:fs';
import { mkdir, readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { writeFileAtomic } from '@vn/util';

/** Where the workflow lands, relative to the project root. */
export const WORKFLOW_FILE = '.github/workflows/vn-pages.yml';
/** Where the committed renderer lands, relative to the project root. */
export const SITEBUILDER_FILE = '.vnstudio/pages/vn-site.mjs';

/**
 * Candidate paths for the bundled renderer, likeliest first. `resources.ts` resolves its files the
 * same way and for the same reason: `__dirname` is `apps/desktop/dist/main` in a packaged build and
 * `apps/desktop/src/main` under jest, and the caller asks for the renderer by name rather than
 * learning which kind of build it is running in.
 *
 * In a packaged build this path is inside the asar. Reading it works because Electron patches
 * `fs`; spawning it would not, which is why nothing here ever runs the file.
 */
function sitebuilderCandidates(): string[] {
  return [
    join(__dirname, 'vn-site.mjs'),
    join(__dirname, '..', '..', 'dist', 'main', 'vn-site.mjs'),
  ];
}

/**
 * The bundled renderer's path in this build. A packaging mistake that drops it is invisible until
 * someone runs the command, so the error says where it looked.
 */
export function sitebuilderPath(): string {
  const found = sitebuilderCandidates().find((path) => existsSync(path));
  if (!found) {
    throw new Error(
      'This build is missing the site builder (vn-site.mjs). Looked in: ' +
        `${sitebuilderCandidates().join(', ')}. Run \`pnpm build\`.`,
    );
  }
  return found;
}

/**
 * The workflow text. `branch` is the repo's branch at install time, so a `main` repo and a
 * `master` repo both get a trigger that fires; `publishBranch` is what the site is pushed to.
 *
 * Only first-party actions are used. The publish is a force-push of a single-commit orphan branch;
 * nothing downstream reads the published branch's past commits. The workflow refuses a publish
 * branch that carries no `.vn-pages` marker, so a hand-built `gh-pages` cannot be destroyed by
 * installing this.
 */
export function workflowYaml(branch: string, publishBranch: string): string {
  return `# Generated by VN Studio. Reinstall from the app to update it.
#
# Renders vngen/build/story.play.json into a static light-novel site and force-pushes it to the
# ${publishBranch} branch. Enable it under Settings > Pages > Deploy from a branch.
name: Publish VN to GitHub Pages
on:
  push:
    branches: [${branch}]
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: vn-pages-\${{ github.ref }}
  cancel-in-progress: false
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Render and publish
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: ${publishBranch}
        run: |
          set -euo pipefail
          remote="https://x-access-token:\${GH_TOKEN}@github.com/\${GITHUB_REPOSITORY}.git"

          # Refuse to overwrite a branch this workflow did not write. Every site it publishes
          # carries a .vn-pages marker at the root; a $PUBLISH_BRANCH without one belongs to
          # somebody else, and the push below would destroy it.
          if [ -n "$(git ls-remote --heads "$remote" "$PUBLISH_BRANCH")" ]; then
            git fetch -q --depth 1 "$remote" "$PUBLISH_BRANCH"
            if ! git cat-file -e FETCH_HEAD:.vn-pages 2>/dev/null; then
              echo "::error::$PUBLISH_BRANCH already exists and was not published by VN Studio. Delete it, or pick another branch, then run this again."
              exit 1
            fi
          fi

          out="$RUNNER_TEMP/site"
          node ${SITEBUILDER_FILE} --project . --out "$out"
          cd "$out"
          git init -q -b "$PUBLISH_BRANCH"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -q -m "Publish site from \${GITHUB_SHA}"
          git push -f "$remote" "$PUBLISH_BRANCH"
`;
}

/**
 * The `.gitattributes` line the committed bundle needs. It is generated output, so a three-way
 * merge of two builds' copies produces a file neither build wrote. Reinstall to resolve one.
 */
const MERGE_ATTRIBUTE = `${SITEBUILDER_FILE} -merge`;

/** Append the bundle's merge attribute unless the file already carries it. */
async function ensureMergeAttribute(root: string): Promise<void> {
  const path = join(root, '.gitattributes');
  let current = '';
  try {
    current = await readFile(path, 'utf8');
  } catch {
    // no .gitattributes yet — writing one with just this line is correct
  }
  if (current.split('\n').some((line) => line.trim() === MERGE_ATTRIBUTE)) return;
  const body = current === '' || current.endsWith('\n') ? current : `${current}\n`;
  await writeFileAtomic(path, `${body}${MERGE_ATTRIBUTE}\n`);
}

export interface PagesState {
  /** Both halves of the publisher are present. */
  installed: boolean;
  /** Installed, but from a different build than this one — reinstalling would change the files. */
  stale: boolean;
}

/**
 * What this project carries today. Staleness is decided by comparing bytes rather than a version
 * stamp, so an edited copy reads as stale too, because reinstalling would overwrite the edit.
 */
export async function pagesState(
  root: string,
  opts: { branch: string; publishBranch: string },
): Promise<PagesState> {
  const workflow = join(root, WORKFLOW_FILE);
  const bundle = join(root, SITEBUILDER_FILE);
  if (!existsSync(workflow) || !existsSync(bundle)) return { installed: false, stale: false };
  const [installedWorkflow, installedBundle, shippedBundle] = await Promise.all([
    readFile(workflow, 'utf8'),
    readFile(bundle, 'utf8'),
    readFile(sitebuilderPath(), 'utf8'),
  ]);
  const stale =
    installedBundle !== shippedBundle ||
    installedWorkflow !== workflowYaml(opts.branch, opts.publishBranch);
  return { installed: true, stale };
}

/**
 * Write both files into the project, overwriting whatever is there, and record the bundle's merge
 * attribute. Returns the workspace-relative paths written: the workflow, the bundle, then
 * `.gitattributes`.
 */
export async function installPages(
  root: string,
  opts: { branch: string; publishBranch: string },
): Promise<string[]> {
  const bundle = await readFile(sitebuilderPath(), 'utf8');
  const files: Array<[string, string]> = [
    [WORKFLOW_FILE, workflowYaml(opts.branch, opts.publishBranch)],
    [SITEBUILDER_FILE, bundle],
  ];
  for (const [rel, body] of files) {
    const path = join(root, rel);
    await mkdir(dirname(path), { recursive: true });
    await writeFileAtomic(path, body);
  }
  await ensureMergeAttribute(root);
  return [...files.map(([rel]) => rel), '.gitattributes'];
}
